### ISSUE TITLE
Create a permission to see and update the "Authors" metabox

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#10]
We should add a capability / permission so that site admins can control who access to the "Authors" metabox

I can imagine situations where someone should be able to edit a post, but not change the author.

**Comment by andergmartins** [comment]
Note for self: For now we check if the use can edit others posts and if it has the capability ppma_edit_orphan_post.

**Comment by andergmartins** [comment]
A user confirmed the capability "edit_others_post" is not required.

**Comment by stevejburge** [comment]
@andergmartins I think a new permission would be helpful

ppma_manage_authors should be focused only on access to the settings

**Comment by stevejburge** [comment]
One more request for this: https://wordpress.org/support/topic/allow-contributor-to-add-more-authors/

> Id like to allow users with the “contributor” role to add more authors to their own posts.
> For now, I can see that only administrators can do this.

**Comment by stevejburge** [comment]
One more customer request for this today

**Comment by stevejburge** [comment]
One more request for this today

**Comment by stevejburge** [comment]
Solved in 3.6 with ppma_edit_post_authors
