### ISSUE TITLE
Can you recreate the file.pot of Authors PRO?

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Authors#1003]
Hi,

I checked the language folder of latest version of Free and Pro that I installed today. The Free version seems complete but the PRO one no. The file.pot inside the language folder is not updated and it miss some strings. 

Can you make a new actualized file.pot for **Author Pro**? So I can start translating because there's no ES-FR-IT translations for the Pro version available so far. How is possible to see from the shot below representing the language pro folder in my local machine

![authors-pro](https://user-images.githubusercontent.com/2352240/198362365-a1a00c4a-2a40-4aaf-8a92-1afe29741f52.jpg)

Thanks,
Angelo

**Comment by ojopaul** [comment]
This is same thing as https://github.com/publishpress/PublishPress-Authors/issues/995 opened 3 days ago and i replied
