### ISSUE TITLE
Update description for fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1010]
We'll need to update details of where this appears:
<img width="1131" alt="Screen Shot 2022-10-31 at 3 58 08 PM" src="https://user-images.githubusercontent.com/3868028/199099198-9febb704-80d5-4d26-bcdd-71ad19b1ac80.png">

Maybe update to:
"This description appears under the fields in the Author Profile screen and helps users understand their choice."
<img width="806" alt="Screen Shot 2022-10-31 at 3 58 39 PM" src="https://user-images.githubusercontent.com/3868028/199099285-00404dff-37d4-4700-b05b-460df30c081b.png">

**Comment by ojopaul** [comment]
@stevejburge The slug field already have description that best describe it.

Does it appear anywhere?

Maybe we need to remove the " in the custom layouts" and leave only "It is used as an author's attribute when referencing the author field"?

Otherwise, do you have suggestion?

**Comment by stevejburge** [comment]
@ojopaul Sure that works: "It is used as an attribute when referencing the author field."
