### ISSUE TITLE
Add insert icon button for Author Boxes social fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1011]
Probably the most common use-case for fields will be adding social links

Can we make it easier to find the right icon?

Maybe we can include some default fields such as Twitter, Facebook, LinkedIn etc to help guide our users?

Maybe there are some pre-constructed fields for Pro users? "Click here to enable the Twitter field"

<img width="927" alt="Screen Shot 2022-10-31 at 4 00 47 PM" src="https://user-images.githubusercontent.com/3868028/199099702-335bfc84-14f4-41ab-bb0d-bf60d2d439ff.png">

**Comment by ojopaul** [comment]
1. Include some default fields such as Twitter, Facebook, LinkedIn for PRO users.
2. The social fields should have default social icons in Author boxes.
3. Profile fields should have turn on/off option
