### ISSUE TITLE
Change menu name to "Author Fields"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1021]
There are so many other uses of "Fields" in WordPress. Let's get more specific:

<img width="167" alt="Screen Shot 2022-11-02 at 1 49 10 PM" src="https://user-images.githubusercontent.com/3868028/199564032-afae239c-a9df-4f8c-9ad5-f42961016503.png">

**Comment by ojopaul** [comment]
Fixed
