### ISSUE TITLE
Add a Pro sidebar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1050]
Can we add a sidebar to "Boxes", "Fields" and "Settings" screens? We can copy the PublishPress Series plugin

<img width="346" alt="Screen Shot 2022-11-10 at 11 53 34 AM" src="https://user-images.githubusercontent.com/3868028/201157607-9f3d62f3-89ed-4eda-8bc2-9e15275aa38a.png">

**Comment by ojopaul** [comment]
@stevejburge where can i copy content for the side bar from https://publishpress.com/authors/?

**Comment by stevejburge** [comment]
@olatechpro With Pro, is custom fields the only feature that's not available in Free?

**Comment by ojopaul** [comment]
Custom field is available in free but with limitation. Not able to add new fields and that seems to be the only thing in pro vs free @stevejburge

**Comment by stevejburge** [comment]
- Add new custom fields
- Add fields for social networks
- Remove PublishPress ads and branding
- Fast, professional support

Does that sound right?

**Comment by ojopaul** [comment]
Okay
