### ISSUE TITLE
Query post by guest author nice name

### ISSUE THREAD

**Issue by jrmcdona** [publishpress/PublishPress-Authors#109]
I read that authors are created using a taxonomy called authors. 

However, when I query a post by the author nice name.  I am getting my post back which assigned to a guest author,  how is that possible?  Also author is null in the output.

![image](https://user-images.githubusercontent.com/4327773/80655726-02a58580-8a45-11ea-9321-b04dd8b0b44f.png)

"Sticky notes team" is the guest author name:

![image](https://user-images.githubusercontent.com/4327773/80655838-46988a80-8a45-11ea-8998-049823449c42.png)

**Comment by stevejburge** [comment]
Hi @jrmcdona Can you see if 3.3.0 Alpha 2 helps with this?
https://github.com/publishpress/PublishPress-Authors/releases/tag/3.3.0-alpha.2

**Comment by andergmartins** [comment]
Hi @jrmcdona we have a new beta. Please, could you check if this is fixed?
You can ignore the alpha.2. We have new bug fixes on this beta. Thanks.

[publishpress-authors-3.3.0-beta.1.zip](https://github.com/publishpress/PublishPress-Authors/files/4561631/publishpress-authors-3.3.0-beta.1.zip)

**Comment by jrmcdona** [comment]
Thanks @andergmartins  @stevejburge  Let me try that out.

How would I get the value of the authors in the save hook function?

https://developer.wordpress.org/reference/hooks/save_post/

**Comment by jrmcdona** [comment]
@andergmartins  @stevejburge   the Alpha plugin failed for me

**Comment by andergmartins** [comment]
Hi @jrmcdona thanks for trying it. 
That is weird... Please, could you confirm you use Composer for handling the plugins? Or are you installing/updating using the plugins page?

**Comment by jrmcdona** [comment]
Hello @andergmartins  I haven't used Composer before.

I deactivated the plugin then manually loaded the new plugin via FTP and tried to activate it again. Then got the error.   Should I just delete the plugin and try again?

**Comment by jrmcdona** [comment]
@andergmartins  On another WordPress project I have, I simply deleted the version I had.  The tried to install the Zip file for the beta.


Warning: Class 'MultipleAuthors\Plugin' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 16

Warning: Class 'MultipleAuthors\Container' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 17

Warning: Class 'MultipleAuthors\Factory' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 18

Warning: Class 'MultipleAuthors\Services' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 19

Warning: Class 'MultipleAuthors\Widget' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 20

Warning: Class 'MultipleAuthors\Classes\Admin_Ajax' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 22

Warning: Class 'MultipleAuthors\Classes\Author_Editor' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 25

Warning: Class 'MultipleAuthors\Classes\Authors_Iterator' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 29

Warning: Class 'MultipleAuthors\Classes\CLI' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 31

Warning: Class 'MultipleAuthors\Classes\Content_Model' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 34

Warning: Class 'MultipleAuthors\Classes\Installer' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 36

Warning: Class 'MultipleAuthors\Classes\Post_Editor' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 37

Warning: Class 'MultipleAuthors\Classes\Query' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 38

Warning: Class 'MultipleAuthors\Classes\Utils' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 39

Warning: Class 'MultipleAuthors\Classes\Objects\Author' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 42

Warning: Class 'MultipleAuthors\Classes\Integrations\RSS' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 46

Warning: Class 'MultipleAuthors\Classes\Integrations\Theme' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\deprecated.php on line 50

Fatal error: Uncaught Error: Class 'MultipleAuthors\Classes\Authors_Iterator' not found in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\functions\coauthors-functions.php:27 Stack trace: #0 D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\functions\template-tags.php(836): include_once() #1 D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\includes.php(38): require_once('D:\\home\\site\\ww...') #2 D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\plugin.php(62): require_once('D:\\home\\site\\ww...') #3 D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\publishpress-authors.php(25): include_once('D:\\home\\site\\ww...') #4 D:\home\site\wwwroot\wp-admin\includes\plugin.php(2223): include('D:\\home\\site\\ww...') #5 D:\home\site\wwwroot\wp-admin\plugins.php(175): plugin_sandbox_scrape('PublishPress-Au...') #6 {main} thrown in D:\home\site\wwwroot\wp-content\plugins\PublishPress-Authors-3.3.0-beta.1\src\functions\coauthors-functions.php on line 27

**Comment by jrmcdona** [comment]
I have rolled back to the other version I had.  So back to the original issue.    Author is null when I query by nicename.  How am I supposed to get the author information?  I use WP Graph QL.


![image](https://user-images.githubusercontent.com/4327773/80895016-01bf5e80-8ca6-11ea-9872-87de05caed26.png)

Maybe your new version will provide this.

**Comment by jrmcdona** [comment]
@andergmartins what shall I do here?  @stevejburge   If this plugin works for my needs, I will need the Pro version because I need to add custom fields for linked in , etc.  But I cannot verify things will work yet.

**Comment by stevejburge** [comment]
@jrmcdona It's just a question of finding the developer time for this, and clearing questions from Pro users.

We have just released 3.3.0 which is worth testing.

**Comment by jrmcdona** [comment]
@stevejburge I purchased the plugin - Agency edition.   3.3 did improve and author is no longer null.

**Comment by stevejburge** [comment]
awesome, thanks for the feedback to help us fix this @jrmcdona
