### ISSUE TITLE
Improve experience with Pro version fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1093]
- I enable the field in "Author Fields"
- I enabled the field in "Author Boxes"

This is the result. Can we default to showing an icon instead of the URL?
<img width="500" alt="Screen Shot 2022-11-21 at 12 30 16 PM" src="https://user-images.githubusercontent.com/3868028/203055825-a3df82a5-0ac3-4684-b232-9ba65622209c.png">

**Comment by ojopaul** [comment]
Edit: To do so, we need to do the following:
- Set facebook html tag to 'link'
- Prepopulate 'Facebook Display Icon' value as without it, nothing will be display
as 
- set 'Facebook Display' to icon

**Comment by ojopaul** [comment]
Additional note:
Default value will only apply to new social fields that haven't been save in editor boxes before.

I won't be creating installer to auto update all social fields as we haven't release the feature yet and should work on new install or new upgrade.

**Comment by ojopaul** [comment]
Fixed in https://github.com/publishpress/PublishPress-Authors/pull/1088
