### ISSUE TITLE
Disable the "Layouts" feature for new installs of Authors Pro

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1099]
Let's allow old users to keep this, but for new users, the "Layouts" feature can be disabled

<img width="346" alt="Screen Shot 2022-11-29 at 11 49 50 AM" src="https://user-images.githubusercontent.com/3868028/204592024-fd06e2fd-2c89-47ee-8f6e-b21d9e8e3603.png">

**Comment by ojopaul** [comment]
@stevejburge I believe we already implement this.

We have the "Enable legacy "Layouts" feature:" in Advanced Settings and it's disabled by default which remove legacy options including the layout or that wasn't working for you?

**Comment by stevejburge** [comment]
@ojopaul Sorry, I can confirm this is fixed
