### ISSUE TITLE
Add new before and after prefix or suffix for author boxes profile fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1119]
Let's allow fields to have a genuine prefix or suffix that is outside of the main icon/link/field area.

For example, this "WordPress Profile" shouldn't be linked
<img width="575" alt="Screen Shot 2022-12-06 at 12 01 41 PM" src="https://user-images.githubusercontent.com/3868028/205977666-838f7402-acb6-4db3-8e6b-5100c3b21b60.png">

**Comment by ojopaul** [comment]
@stevejburge for a confirmation, we're adding new two additional fields for this?

**Comment by stevejburge** [comment]
@ojopaul Yes, please
