### ISSUE TITLE
Getting authors values from save_post hook

### ISSUE THREAD

**Issue by jrmcdona** [publishpress/PublishPress-Authors#113]
How would I get the value of the authors in the save hook function?

https://developer.wordpress.org/reference/hooks/save_post/

**Comment by jrmcdona** [comment]
@andergmartins  is this possible?

**Comment by jrmcdona** [comment]
@stevejburge   here is more details.   If you see my GIST you can see an example of my save_post hook.
I am getting information about the POST and sending it over to another service where I do different things, such as localiation.   

What I cannot figure out is how to get the Guest author in the save hook.   Where would I find it on the Post object?

https://gist.github.com/jrmcdona/884d0ce8d78db9c12358fda9a278a20d

**Comment by andergmartins** [comment]
Hi @jrmcdona,

For multiple authors you should ignore the post_author property.
You can get a list of authors using the function we provide: 

`$authors = get_multiple_authors($postId);`

It returns an array so you can iterate in a loop. So if you need to get the first author, you can get the first item of the array.

Please, let me know if you need more details or more specific help with that code.

**Comment by jrmcdona** [comment]
Works great.

**Comment by andergmartins** [comment]
Cool, thanks for the feedback @jrmcdona
