### ISSUE TITLE
Improve message for mapping authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1131]
A couple of people have been confused by this message. We should explain in more detail:
<img width="754" alt="Screen Shot 2022-12-20 at 11 27 55 AM" src="https://user-images.githubusercontent.com/3868028/208716632-ffbb46b2-b26c-4e71-92b5-7eacfedf1e62.png">

**Comment by ojopaul** [comment]
@stevejburge Improvement suggestion?

**Comment by stevejburge** [comment]
"Sorry, this WordPress user is already mapped to another Author. By default, each user can only be connected to one Author profile."
