### ISSUE TITLE
"Author box shortcode" documentation contains shortcodes  with "author" instead of "authors" which makes codes unworkable

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1148]
**"Author box shortcode" documentation presents shortcodes  with "author" instead of "authors" in them which makes codes unworkable:** 

![Screenshot_20221230_110348](https://user-images.githubusercontent.com/113949004/210104709-1aba30eb-662c-4d00-8076-9db0d34c33b5.png)

**So if I insert this code mentioned in documentation in Gutenberg editor block in "edit post" page:**
 
![Screenshot_20221230_111613](https://user-images.githubusercontent.com/113949004/210105106-e847b3bf-f1f7-4aac-b748-c7320d9745b0.png)

 **I get the code displayed in the post page instead of the author's name:**

![Screenshot_20221230_112035](https://user-images.githubusercontent.com/113949004/210106614-edcd82cc-4c7d-4fad-90ee-a80dd8e8cffa.png)

**but if i display same line of code with "authors" instead of "author" in them - everything works great, and author is displayed in the post**

![Screenshot_20221230_112305](https://user-images.githubusercontent.com/113949004/210105463-64791610-ab84-488a-a542-8d4b11e7307c.png)

![Screenshot_20221230_112329](https://user-images.githubusercontent.com/113949004/210105468-2c1d44e6-50b4-4683-a320-ff78a907b181.png)

**Comment by stevejburge** [comment]
Thanks for catching that @lenacaz
