### ISSUE TITLE
Add fallback field for [publishpress_authors_data] shortcode

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1150]
**"Authors Data Shortcode" documentation contains description of shortcode allowing to display first name of each author attached to the post:** 

![Screenshot_20221230_042836](https://user-images.githubusercontent.com/113949004/210119881-151f8302-9eec-4db9-9b90-827d37295cba.png)

**There are 2 authors attached to my post: "Marina Sokol Editor and "Matthew Connel":"**

![Screenshot_20221230_044731](https://user-images.githubusercontent.com/113949004/210120112-dee1cf18-c1af-4abc-9cc6-cb1de9b8c0ce.png)

**When I insert mentioned shortcode in Gutenberg editor block and click "update", only one first name appears on the post page - Marina. First name of the second author "Matthew" is not present:** 

![Screenshot_20221230_045127](https://user-images.githubusercontent.com/113949004/210120157-71781451-2130-41c2-893e-f46663a7fa4c.png)

**If I add 1 more author in the post - "Alina Drozd Subscriber" - so now I have total of 3 authors, only first name of first and last author get displayed in the post page, no space between them (after comma punctuation mark:)**

![Screenshot_20221230_045939](https://user-images.githubusercontent.com/113949004/210120462-7ac0cfd6-a05d-49a3-bd61-a717cc23c4c8.png)

**Comment by ojopaul** [comment]
@stevejburge @rizaardiyanto1412 Can you test this issue? I'm not getting the issue while testing on my end

**Comment by rizaardiyanto1412** [comment]
I'm able to replicate this issue @ojopaul 
I'm on PHP 8.0 and Author 4.1.1

**Comment by ojopaul** [comment]
Thanks @rizaardiyanto1412 
For confirmation, when you use [publishpress_authors_data field="first_name"] in a post with multiple author, 

1. Only one out of the added Author is showing?
2. Are the two Authors Guest Authors or Users or mixed?

**Comment by rizaardiyanto1412** [comment]
Sorry false alarm @ojopaul 
I tested on other environment and it works fine. 

On my case, the 2nd author does not have a first name in the Author Profile. Maybe that's also the same case with you @lenacaz ?
![image](https://user-images.githubusercontent.com/83811723/214305303-f5f6ad83-5377-4041-bed2-c6b1b31a73d0.png)

**Comment by stevejburge** [comment]
Sure, that's a good idea
