### ISSUE TITLE
Shortcode within a Query-Loop-Block does not work

### ISSUE THREAD

**Issue by errotu** [publishpress/PublishPress-Authors#1151]
## Expected Behavior
When using the Query-Loop-Block to display blog posts, the Publish Press-Authors shortcode should pull information of the blog post displayed by the block.

## Current Behavior
The author of the single page is shown, not the author of the blog post(s) pulled by the Query-Loop-Block.

## Context
I am using the Full-Site-Editing possibilities of the Gutenberg-Editor in current Wordpress themes (namely Twenty Twenty-Three). By using the [Query Loop-Block](https://wordpress.org/support/article/query-loop-block/), I show recent blog posts on my home page. The [Post Author Block](https://wordpress.org/support/article/post-author-block/) (as alternative to the Publish Press Authors-Shortcode), does only display a single author and not multiple authors of a post.

Thanks a lot for all your great work!

**Comment by stevejburge** [comment]
@errotu Please read this and follow up if you think it remains a bug: https://publishpress.com/knowledge-base/authors-data-backup/

**Comment by errotu** [comment]
I do think it remains a bug (or a possible feature request, depends on what you'd expect). The knowledge base article does not address the particular issue of invoking the Publish Press author(s) within a Query Loop block in the Gutenberg editor. 
It seems to me like it's currently not possible to display PP authors within the Query Loop block (which is crucial for full-site-editing).

**Comment by errotu** [comment]
Hi @stevejburge, did you have any time to look into this issue? Is my description sufficiently clear? Or does the plugin simply not support the Query Loop block of the Gutenberg editor?

**Comment by stevejburge** [comment]
@errotu Authors are stored in a taxonomy. This should work under the "Filters" area:

<img width="710" alt="Screen Shot 2023-01-16 at 8 57 16 AM" src="https://user-images.githubusercontent.com/3868028/212695040-6a7829b8-cc90-4f75-934e-70fd77ea2164.png">

**Comment by errotu** [comment]
Thanks a lot for your efforts and the quick replies!

I am afraid the shortcode doesn't solve my issue. Maybe I have to describe the usecase in more detail: I am using the Query-Loop-block to display the last two posts of different categories on my homepage. Each post should be displayed with its title, its featured image and the Publish Press authors who are assigned to the respective post.

It should look like this:

- Post 1
    - Title [using the [Post Title Block](https://wordpress.org/support/article/post-title-block/)]
    - Featured Image [using the [Post Featured Image Block](https://wordpress.org/support/article/post-featured-image-block/)]
    - Publish Press Authors [not working]
- Post 2
    - Title [using the [Post Title Block](https://wordpress.org/support/article/post-title-block/)]
    - Featured Image [using the [Post Featured Image Block](https://wordpress.org/support/article/post-featured-image-block/)]
    - Publish Press Authors [not working]

When using the authors list-shortcode (as you propose), all authors are displayed (not only the ones of the respective posts). When I use the authors box-shortcode, only the one of the _page_, not the authors of the respective _posts_ are shown.

**Comment by stevejburge** [comment]
@errotu yes, this isn't a bug for Github, it's really a support question. I'd recommend using either our Free or Pro support channels.

**Comment by errotu** [comment]
Okay, thank you for the clarification!
