### ISSUE TITLE
Update Author Pages Schema to Person Schema type

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1163]
I've tested with this Yoast and Rank Math, and on a test site plus a customer site

Enable our Author Pages:
<img width="840" alt="Screen Shot 2023-01-09 at 7 49 21 AM" src="https://user-images.githubusercontent.com/3868028/211311745-a76221c4-7205-4821-b105-c2d455572335.png">

The schema no longer works:
<img width="853" alt="Screen Shot 2023-01-09 at 7 47 01 AM" src="https://user-images.githubusercontent.com/3868028/211311831-921571e1-d769-477c-abe5-4daef6252a64.png">

**Comment by ojopaul** [comment]
@stevejburge Click any of the panel to expose the schema items.

![panel](https://user-images.githubusercontent.com/92122385/211756173-d0d839df-8b93-4ccf-80bd-f9fd221ce00f.jpg)

**Comment by stevejburge** [comment]
@ojopaul Sorry, I should have posted the full results, but the Author schema data isn't there

This is what we get when our Author Pages feature is disabled:


<img width="766" alt="Screen Shot 2023-01-11 at 7 54 00 AM" src="https://user-images.githubusercontent.com/3868028/211811502-59d594dc-b385-4768-8f16-2901f090753a.png">

**Comment by ojopaul** [comment]
@stevejburge Okay, i get it now.

The title was only misleading as it implies Schema is not showing.

I'll work on making it showing Person schema instead of term.
