### ISSUE TITLE
Can't use HTML in Author Boxes Bio

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1175]
This is an odd bug .... it's possible to use HTML in author boxes if loaded via shortcode, but not the regular author box

<img width="852" alt="Screen Shot 2023-01-12 at 9 44 47 AM" src="https://user-images.githubusercontent.com/3868028/212097561-9a4d4772-e3b4-4351-a36c-99a5f52a4d6b.png">

Here's the "Biographical Info" for that author
<img width="820" alt="Screen Shot 2023-01-12 at 9 46 49 AM" src="https://user-images.githubusercontent.com/3868028/212097692-46e3d466-4882-449e-b1f8-4c5689ac20b2.png">

**Comment by rizaardiyanto1412** [comment]
What shortcode you used @stevejburge ? Because I cannot replicate this
![image](https://user-images.githubusercontent.com/83811723/212105093-80325fee-c906-4a0d-8948-c41fd9240ef9.png)

**Comment by ojopaul** [comment]
@rizaardiyanto1412 What shortcode produces the issue?

I can confirm the issue for non shortcode but wasn't able to see the shortcode own

**Comment by rizaardiyanto1412** [comment]
I use the regular shortcode @ojopaul [publishpress_authors_box]

**Comment by ojopaul** [comment]
Okay, thanks @rizaardiyanto1412
