### ISSUE TITLE
Editable fields containing numeric values on "Author Editor Box" page allow saving negative values

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1178]
Expected results: While saving negative value in numeric editable fields of "Author Editor Box" page, error message "Value must be greater than or equal to 0" must appear. 

Actual results:  Plugin allows saving negative values in numeric editable fields "Author Editor Box" page. 

Note: Same error is present for other editable numeric fields from "Edit Author Box" page:

- "Avatar size", "Border width" fields from "Avatar" window of "Edit Author Box" page
- "Size", "Line Height"(px) fields from "Display Name" window of "Edit Author Box" page 
-  "Size", "Line Height" fields from "Bibliographical Info" window of "Edit Author Box" page 
- "Size", "Line Height" fields from "Meta" window of "Edit Author Box" page 
- "Recent Post Title Border Width", "Limit", "Size", "Line Height", from "Author Recent Posts" window of "Edit Author Box" page 
- "Margin Top", "Margin Bottom", "Margin Left", "Margin Right", "Padding Top", "Padding Bottom", "Padding Left", "Padding Right", "Border Radius", "Shadow Horizontal Offset", "Shadow Vertical Offset", "Shadow Blur", "Shadow spread" fields of "Box Layout" window of "Edit Author Box" page. 
 

Steps to reproduce:

- Click "Authors" menu
- Choose "Author Boxes" menu item
- Click on checkbox "Boxed" (Note: same issue present if "Centered", "Inline", "Inline with avatars", "Simple list" layout chosen).
- Click on "Edit" button
- Enter negative values in "Bottom space", "Size", "Line Height" fields
- Click "Update" button

![Screenshot_20230113_105535](https://user-images.githubusercontent.com/113949004/212403438-73cdae45-2978-42e5-9c67-43b1f4150d23.png)

![Screenshot_20230113_105612](https://user-images.githubusercontent.com/113949004/212403445-49d32cd9-5192-4242-b85f-4791a1db6e94.png)

**Comment by stevejburge** [comment]
Thanks @lenacaz. Negative value are valid values in styling and so we can leave these
