### ISSUE TITLE
Border Radius not working correctly

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1188]
Feedback: 

> I am not quite sure how "Border Radius (%)" feature of "Author box editor" is supposed to work, so would just like to bring to your attention that up to certain percentage (for example, value up to 10) avatar shape changes to square, instead of circle. Values between 10-50% display avatar in the form of square with rounded edges   If value of the "Border Radius (%)" chosen over 50% - it displays as circle. 

I can confirm this. I set the border radius to 5:
<img width="602" alt="Screen Shot 2023-01-17 at 12 12 43 PM" src="https://user-images.githubusercontent.com/3868028/212966246-8e84d605-c3c8-439e-aedd-ce5e0bf53005.png">

This was the end result:
![Screen Shot 2023-01-17 at 12 12 03 PM](https://user-images.githubusercontent.com/3868028/212966104-3c345059-34ea-43a7-a5f2-ab9fc0f8b399.png)

**Comment by ojopaul** [comment]
@stevejburge radius is in percentage and how's it suppose to work or what do you have in mind?

If you create a custom image(outside authors) and set border radius as 5%, is the result different?
