### ISSUE TITLE
Add "SameAs" schema option to links

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1189]
Can we allow users to designate some fields with the "sameAS" schema option so that they appear in the schema data

![image](https://user-images.githubusercontent.com/3868028/213243325-3ea3f9a5-c5d3-4f7c-8754-1d928ebac116.png)

**Comment by ojopaul** [comment]
@stevejburge Following normal standard, all url type field are supposed to appear in same as profile fields in schema fields but if we feel like adding the options, does average user even understand what this is and what should the option be like?
- A checkbox with label that read SameAs?
