### ISSUE TITLE
Author Pages show "Author" despite the site being translated

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1193]
When you install PublishPress Authors, the plugin overrides the "Author" text on Author Pages.

So in the example of this user, his site is in Norwegian so the text should be "Forfatter". Instead the word "Author" shows
https://wordpress.org/support/topic/translation-issues-60/

This isn't a problem if our plugin does have a translation, but the problem appears when using a language that isn't available for Authors.

**Comment by audunmb** [comment]
As noted in the wordpress forums, you can solve this by using wordpress core translations instead of plugin translations whenever available.

**Comment by ojopaul** [comment]
closing this for https://github.com/publishpress/PublishPress-Authors/issues/1194
