### ISSUE TITLE
Not possible to edit the default Administrator

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1195]
There is no "Edit Author Profile" link for the default author:
![Screen Shot 2023-01-20 at 10 34 11 AM](https://user-images.githubusercontent.com/3868028/213739494-c6276de1-c67d-47fe-ab67-a2d0bef4c6bb.png)

**Comment by ojopaul** [comment]
@stevejburge When you hover over the name, what options are available or nothing happen, if nothing happen, can you check your console incase there's an error?

I'm trying to recreate this issue by installing Authors on new site but all options are showing for me.

![hover](https://user-images.githubusercontent.com/92122385/214563958-1988c28e-ab8a-4f92-b26b-dc23bcfde50b.jpg)
