### ISSUE TITLE
"Authors list" widget does not display list of authors properly in "Inline" and "Inline with Avatars" settings

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1245]
When "Inline" or "Inline with Avatars" settings are chosen for Authors list display Widget , list of names does not appear in proper way : 

**"Inline" option chosen:** 

![Screenshot_20230205_093327](https://user-images.githubusercontent.com/113949004/216892673-fc727678-b98c-4a41-a49c-7205595f310e.png)

**"Inline" with Avatars option chosen:**

![Screenshot_20230205_093407](https://user-images.githubusercontent.com/113949004/216892774-11db985d-b519-4a37-a38d-db049f86ee5d.png)

**Comment by ojopaul** [comment]
@stevejburge I'm wondering if this issue still exists especially now that we have Authors separator as a settings?

**Comment by stevejburge** [comment]
@ojopaul Yes, let's close and move on
