### ISSUE TITLE
Compatibility with Admin Menu Editor

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1247]
If you have https://wordpress.org/plugins/admin-menu-editor/ plugin installed, the first submenu on Author will show incorrect link
![image](https://user-images.githubusercontent.com/83811723/216955108-b18df6d1-1f56-4b6c-b3ff-e8169cd28924.png)

The first author menu should be hidden

**Comment by stevejburge** [comment]
@rizaardiyanto1412 This sounds more like a bug in their plugin?

**Comment by rizaardiyanto1412** [comment]
Thanks @stevejburge I'm confirming with them: https://wordpress.org/support/topic/menu-should-be-hidden/

**Comment by rizaardiyanto1412** [comment]
@stevejburge this is from their reply. Is there anything we can do from our side?

> This is a plugin conflict, and it’s not easily fixable.
> 
> The first “Authors” submenu item is an existing item. Apparently, PublishPress Authors normally explicitly removes the item (in publishpress-authors/src/modules/multiple-authors/multiple-authors.php, lines #447 to #456 in version 4.1.2). However, when Admin Menu Editor is active, the custom admin menu configuration is already done at that point, so that attempt to modify the admin menu has no effect.
> 
> Usually, I would add the item to the internal blacklist that AME uses to hide menu items like this. That won’t work in this case because the top-level “Authors” menu has the same slug as the first “Authors” submenu item: hiding the submenu item would also hide the top-level menu.

**Comment by ojopaul** [comment]
@stevejburge @rizaardiyanto1412 Plugins Authors are supposed to be responsible for such compatibility fixes and not us.

I'll try to use JavasCript to replace the link here since they fail to do so and hopefully that fixes it.
