### ISSUE TITLE
"Profile field" instead of "Author field" in documentation

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1259]
"How to add Author fields" part of documentation contains Step 3 - "Add field to your layout". It says "Go to profile Fields Tab" - in reality "Author Fields" tab : 

![Screenshot_20230215_090808](https://user-images.githubusercontent.com/113949004/219102090-2336ca19-f4af-4ef3-acc2-e400f98dd2b9.png)

![Screenshot_20230215_090821](https://user-images.githubusercontent.com/113949004/219102123-488137c6-0ded-42f4-817a-82902b06f14a.png)

**Comment by stevejburge** [comment]
Thanks @lenacaz
