### ISSUE TITLE
Ignore cache on authors metabox AND/OR ensure cache get cleared on save_post

### ISSUE THREAD

**Issue by anekola** [publishpress/PublishPress-Authors#1270]
Whenever my team attempts to save anything in the authors meta box it doesn't take because the cache isn't cleared. My first thought is that this field doesn't need to pull from the cache, since it's in the admin:

https://github.com/publishpress/PublishPress-Authors/blob/7c4ebaf181f68dcfb7869eaa226bfc0bfb872399/src/core/Classes/Post_Editor.php#L237

`$authors = get_post_authors( '', true );`

However, that doesn't fully solve the problem because it doesn't answer the question — why can't I clear this field from the object cache? We use WordPress VIP as a host, which provides a suite of caching assistance, but I cannot seem to clear `get_post_authors:authors` from the cache: https://docs.wpvip.com/technical-references/caching/

I took to setting the cache in this flush cache option; which seems to do the trick:

```
function my_clear_author_cache( $post_id ) {
	$authorsInstances = get_post_authors( $post_id, true );
	wp_cache_set( $post_id, $authorsInstances, 'get_post_authors:authors');
}
add_action( 'publishpress_authors_flush_cache', 'my_clear_author_cache', 15, 1 );
```

**Comment by stevejburge** [comment]
Thanks for posting the issue @anekola. We don't have access to WordPress VIP so can't confirm any hosting-specific fixes, but we can look at this in general.

**Comment by miscs** [comment]
@stevejburge we have the same problem in a self hosted environment using REDIS as an object cache
