### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_avatar_url()

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1273]
Step to replicate:
1. Install PP Author + Rankmath + [Subscribe to comment](https://wordpress.org/plugins/subscribe-to-comments-reloaded/)
2. On a post, there is this link
![image](https://user-images.githubusercontent.com/83811723/221157173-4d75e9bd-82d2-49a5-9e42-47d0127e11e6.png)
3. Click it, and you will see this error
![image](https://user-images.githubusercontent.com/83811723/221157245-78f57ec7-ef39-4587-9a1f-0f078b41c537.png)

Original report: https://wordpress.org/support/topic/fatal-error-uncaught-error-call-to-a-member-function-get_avatar_url-2/

**Comment by ojopaul** [comment]
@terrificobjects are you receiving same message as in above screenshot?

If not, can you provide the message of the error you're receiving as it could be something else.

**Comment by ojopaul** [comment]
@terrificobjects Apologies for missing this in the last update.

The fix has been commited to the repository now and will surely be part of next update.

You can test the package file attached to my reply for confirmation.

[publishpress-authors-4.1.2.zip](https://github.com/publishpress/PublishPress-Authors/files/11087862/publishpress-authors-4.1.2.zip)
