### ISSUE TITLE
Unfinished sentence in "Update the Authors Byline in your Theme" part of documentation. 

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1275]
"Update the Authors Byline in your Theme" part of documentation from "Authors and Themes" contains unfinished sentence:

"So to show multiple authors we need to replace the "

![Screenshot_20230227_102246](https://user-images.githubusercontent.com/113949004/221651118-b4d4024b-0a6c-4fd4-af16-e001ad43edf1.png)

**Comment by stevejburge** [comment]
Thanks @lenacaz
