### ISSUE TITLE
Discrepancy between "Plugin Capabilities – PublishPress Authors" window in Documentation and in Reality

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1279]
In "Authors Permissions " part of  documentation it's stated that: " Free version of PublishPress Authors has three permissions to control access to the plugin's features. The Pro version adds two more" . 

**In Documentation plugin capabilities window contains 3 permissions: **

 
![Screenshot_20230227_104946](https://user-images.githubusercontent.com/113949004/221776288-85142232-a427-4a4d-b51a-d972517fda3d.png)

**In reality, there are 4, names of Permissions do not match:** 

![Screenshot_20230227_105219](https://user-images.githubusercontent.com/113949004/221776639-6ad0bcae-34ff-4502-8ed0-a9dc1c3c9ef8.png)

**Comment by stevejburge** [comment]
Thanks @lenacaz
