### ISSUE TITLE
"Author Profile" Menu does not appear in "Subscriber" and "Contributor" users' Dashboards. "

### ISSUE THREAD

**Issue by lenacaz** [publishpress/PublishPress-Authors#1282]
Expected results: based on documentation, once Author is mapped to certain user, "Author Profile" will appear in that user's profile. 
Actual results: "Author Profile" Menu does not appear in "Subscriber" and "Contributor" users' dashboards. ":

**Contributor's dashboard after mapping Author to Contributor user**

![Screenshot 2023-03-01 113312](https://user-images.githubusercontent.com/113949004/222245227-7413894f-54b4-49ee-99b2-fa525c96e71b.png)

**Subscriber's dashboard after mapping Author to Subscriber user**

![image](https://user-images.githubusercontent.com/113949004/222245431-3ef66542-93ad-49f7-ae46-fc3f5b0ab39c.png)

**Comment by ojopaul** [comment]
@stevejburge @lenacaz Does the roles has `ppma_edit_own_profile` capability enabled for them?

**Comment by stevejburge** [comment]
@ojopaul Let's close this in favor of the same issue here: https://github.com/publishpress/PublishPress-Authors/issues/1443
