### ISSUE TITLE
Add User Account option for Guest Authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1287]
The Authorship plugin creates user accounts for Guest Authors in a Guest Author role:
https://github.com/humanmade/authorship

<img width="1209" alt="Screenshot 2023-03-07 at 10 24 18 AM" src="https://user-images.githubusercontent.com/3868028/223467644-b453978b-b6b1-4a2a-ad59-2dc5f6e7312c.png">

> 
> Existing plugins that provide guest author functionality make a distinction between a guest author and a real WordPress user. A guest author exists only as a taxonomy term, which complicates the UX and creates inconsistencies and duplication in the data.
> 
> Authorship creates a real WordPress user account for each guest author, which provides several advantages:
> 
>     No custom administration screens for managing guest authors separately from regular users
>     Plugins that customise user profiles work for guest authors too
>     Consistent data structure - you only ever deal with WP_User objects
>     No need to keep data in sync between a user and their "author" profile
>     Promoting a guest author to a functional user is done just by changing their user role

**Comment by stevejburge** [comment]
I keep coming across situations where this would be useful. I think this should be an optional feature and disabled by default.

Maybe a new setting? "Generate Dummy User Accounts for Guest Authors"

Then a Maintenance button to generate dummy accounts for existing guest authors.

**Comment by ojopaul** [comment]
@stevejburge Does this issue still stand, generate user account for Guest Authors?

**Comment by stevejburge** [comment]
@ojopaul Yes, this will be a useful feature, please

In particular, it can useful to help support themes that don't integrate with PublishPress Authors.
