### ISSUE TITLE
Set a default color for icons / fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1288]
I created a new icon for this guide

By default, it didn't show:
<img width="527" alt="Screenshot 2023-03-13 at 1 59 28 PM" src="https://user-images.githubusercontent.com/3868028/224788838-ad038746-065d-47cd-8618-381a5b64d248.png">

I had to manually choose a color, which took some time to figure out
<img width="876" alt="Screenshot 2023-03-13 at 2 00 08 PM" src="https://user-images.githubusercontent.com/3868028/224788870-7b5a2c3f-5c2a-46f4-b27f-b687a326a04d.png">

I wonder if we need default colors? Should the color options be together and easier to find?

**Comment by ojopaul** [comment]
@stevejburge What section/field is this talking about?

**Comment by stevejburge** [comment]
Returning to this issue after some time, perhaps we should just make the
color settings easier to find?

Move them closer to the top of the settings.

**Comment by ojopaul** [comment]
@stevejburge Can you answer my question?

**Comment by stevejburge** [comment]
@ojopaul Let's leave this for now. It's one of those problems that I forgot after 6 months
