### ISSUE TITLE
Display few authors on backend list

### ISSUE THREAD

**Issue by AntonioS30** [publishpress/PublishPress-Authors#1293]
Dear staff i’v about 20 authors on my site and when i’m creating a post, the plugin does not show all of the authors, it stop about at 15 authors in the list menu. How to fix it to display all?

**Comment by stevejburge** [comment]
@AntonioS30 Sorry, our Github repo is for bugs, not support tickets about individual sites.

If this is a bug you have tested and can recreate on multiple sites, please let us know.
