### ISSUE TITLE
Showing multiple author in RSS Feed

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1299]
> Dear support,
> 
> Another question about showing multiple authors (co-authors) in the RSS feeds - last week you provided us with the custom code that we could try implementing in order to push all the authors to the RSS feeds https://warrengroom.com/website-development/co-authors-wordpress-rss-feeds/
> We tried that, but the result we got was not exactly what we were looking for:
> 
> <dc:creator><![CDATA[Author1 and Author2]]></dc:creator>
> 
> What we are looking for is a separate line/separate <dc:creator> element for each of the authors. Is it possible with your plugin and would you be able to provide us with a custom solution?

Ticket: https://secure.helpscout.net/conversation/2192401926/179370?folderId=6932143

**Comment by stevejburge** [comment]
This can be solved by creating real users for guest authors
