### ISSUE TITLE
Author Box Editor disappeared (Free version)

### ISSUE THREAD

**Issue by errotu** [publishpress/PublishPress-Authors#1309]
## Expected Behavior

Being able to edit the Author Boxes via the Author Box Editor.

## Current Behavior

I am pretty sure there was an Author Box Editor [as described here](https://publishpress.com/knowledge-base/customize-author-boxes/) in the free version a couple of months ago, but now it seems to be gone. Am I mistaken, is this a bug or was it removed/moved to the Pro Version?

**Comment by stevejburge** [comment]
Hi @errotu. Sorry, please follow our support guide:
https://publishpress.com/publishpress-support/
> 
[Github is] the option is for genuine bugs that can be reproduced on other sites. This is not for support questions about your site. For questions about your site, please choose another option on this page.

**Comment by errotu** [comment]
I am not sure what it was caused by, but this seems to be a bug to me. However, for anyone else who might be facing this issue: I was able to access the Author Box Editor by directly opening its URL: /wp-admin/edit.php?post_type=ppma_boxes
