### ISSUE TITLE
Sidebar box missing header missing on authors boxes editor page

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1318]
Sometimes this box is missing a header:
![Screenshot 2023-05-05 at 8 47 54 AM](https://user-images.githubusercontent.com/3868028/236461614-5fc594be-2533-45b8-b186-c4c84695805a.png)

**Comment by ojopaul** [comment]
@stevejburge I've checked but couldn't see any reason it should be missing

**Comment by stevejburge** [comment]
@ojopaul This problems still exists on today's version

For example:
/wp-admin/post.php?post=14&action=edit
/wp-admin/post.php?post=10&action=edit

**Comment by ojopaul** [comment]
Okay @stevejburge Thanks for confirming the pages.

I was only checking settings page before
