### ISSUE TITLE
Automatically add the Author profile to their URLs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#132]
We automatically add the author profile beneath post and pages.

We should automatically add it to Authors' URL pages:
![Screen Shot 2020-05-26 at 1 30 55 PM](https://user-images.githubusercontent.com/3868028/82932061-dd2d6e00-9f55-11ea-8593-e461dc2c4941.png)

**Comment by andergmartins** [comment]
Maybe we could have an option in the settings to enable/disable this? I'm not sure it would work well for every theme.

**Comment by mdmag** [comment]
@stevejburge 

> We automatically add the author profile beneath post and pages.

Do we talk here about the author widget or something else?

**Comment by mdmag** [comment]
Ah, I got it now. I will work on it but waiting for your feedback on @andergmartins  question.

**Comment by stevejburge** [comment]
@mdmag Thanks. I talked with Anderson and he is clear on this now.

When it comes to a setting to enable / disable this, we can move to this issue https://github.com/publishpress/PublishPress-Authors/issues/230

**Comment by mdmag** [comment]
@stevejburge No problem, I will integrate this setting also.

**Comment by muhammedmagdi** [comment]
@stevejburge  @andergmartins  I can't find any proper hook on which I can hook this author box on the author profile page.
Perhaps the only hook I see that will work in this case is: `wp-footer` .. Anderson, what do you think?

**Comment by muhammedmagdi** [comment]
@andergmartins  @stevejburge I can't find a proper hook on which we can add the author profile on the author page.
I found `wp_footer` but it adds the author profile after the footer. I have read that get_footer may be used but not all themes support this.
Anderson, what do you think?

**Comment by stevejburge** [comment]
@muhammedmagdi Thanks for your work on this. I think we may have to move onto the next task ... this may be something that has to be done on the theme level
