### ISSUE TITLE
Update author mapped user description

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1321]
If I disable then enable the "Enable Guest Authors" box again, it's not working correctly:
![Screenshot 2023-05-05 at 8 53 06 AM](https://user-images.githubusercontent.com/3868028/236462624-d08566a4-d9db-4b8e-80fe-40e5c1d9185b.png)

**Comment by ojopaul** [comment]
Isn't that what it's for? @stevejburge

**Comment by stevejburge** [comment]
We did have this text before:

"You don’t have to choose a Mapped User. Leave this choice blank and you can create a Guest Author with no WordPress account."
![Screenshot 2023-05-05 at 10 12 22 AM](https://user-images.githubusercontent.com/3868028/236482528-d73c0857-bc9b-4ac6-8d8b-024ccabec669.png)

**Comment by ojopaul** [comment]
Lol, this is a post from you on https://github.com/publishpress/PublishPress-Authors/issues/1310 asking for it to be removed

<img width="768" alt="comm" src="https://user-images.githubusercontent.com/92122385/236486093-a016c05b-0644-4852-a560-bf7618e3d034.png">

Anyways, to make the conversation short, maybe add comment on new changes?

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul Sorry for the confusion.

Can we leave the previous text in place if the Guest Author feature is enabled?
