### ISSUE TITLE
Support legacy layout slug in author boxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1334]
I guess we remove the "Authors Box" area?

What should happen with "Author List" which uses layout="boxed"
<img width="1062" alt="Screenshot 2023-05-10 at 9 18 02 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/d139096e-7800-4726-ad83-d20dc4ab8cfd">

**Comment by ojopaul** [comment]
We have the following legacy layouts:
- simple_list 
- centered 
- boxed inline 
- inline_avatar

We need to support the slugs in Author boxes so their Author boxes counter part will be loaded.
