### ISSUE TITLE
Last column has different size on Author List

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1345]
Step to replicate:
1. Make sure you have many Authors
2. Add this shortcode:
[publishpress_authors_list layout="ppma_boxes_489" layout_columns="4" show_title="false" show_empty="0"]

Note: ppma_boxes_489 for me is Centered Author Box:
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/d6ef85a1-6bc5-4b61-bde2-96092bf17e2a)

3. Observe issue, 4th column relatively small compare to other column

![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/fa592313-02db-403a-ad79-a93579583eae)

![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/ca6c67f5-5174-40ef-a9ee-78401cfcce3e)

**Comment by ojopaul** [comment]
@rizaardiyanto1412 It's funny that even I that added layout_columns to author's boxes layout doesn't know it works with other layouts except the author recents.

I'll check the issue now.
