### ISSUE TITLE
Quick Edit issue with Elementor

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1346]
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/c781e329-c0ba-42d2-9d20-931dc61e612d)

![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/0bab408d-22ef-449a-91cf-c5380f4ba6a0)

When having Elementor active, the Author position in quick edit is messed up. Is it possible to fix it from our side?

**Comment by ojopaul** [comment]
@rizaardiyanto1412 @stevejburge I don't think this should be referred to as a bug, element position in quick edit is not static, it depends on how many plugins are added or filters are adding item to the quick edit and position depends on where and when each filter runs.

What you see in both screen may be different for other users as well who have plugins that add additional items to quick edit thereby shifting Authors quick edit positioning

**Comment by rizaardiyanto1412** [comment]
Noted. Thanks for the information @ojopaul 

I guess we can close it then.
