### ISSUE TITLE
Missed semicolon on generated theme template

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1352]
There’s a glitch in the code which is generated for the theme template file. A “;” is missing at line 20:
$post_id = isset($ppma_template_authors_post->ID) ? $ppma_template_authors_post->ID : $post->ID

Which cause the next line to fail and give an error for the IF statement.

Hope it helps.

**Comment by ojopaul** [comment]
From: https://wordpress.org/support/topic/error-on-generated-theme-template/
