### ISSUE TITLE
Remove "Create default Author Boxes" maintenance button

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1371]
This button doesn't work with the new Author Box system. Should we remove it?

<img width="656" alt="Screenshot 2023-06-02 at 5 00 04 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/fc8160b4-feaa-4794-807a-513bbbdfd354">

**Comment by ojopaul** [comment]
Current default author boxes will always be added when removed now that's part of the layout. So, removing this option instead
