### ISSUE TITLE
Move "Author Bio" to the bottom of the "Edit My Author Profile" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1372]
Should we update our Author Profiles so that they more clearly match the WordPress profiles?
- Update the names
- Update the order
![authors](https://github.com/publishpress/PublishPress-Authors/assets/3868028/764ebdce-6b86-4dbf-8ecf-511237e776b9)

**Comment by ojopaul** [comment]
@stevejburge The names and order are coming from Author fields and not manual texts
/wp-admin/edit.php?post_type=ppmacf_field
