### ISSUE TITLE
Add author boxes author separator field

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1379]
Could we add a text separator field to spread out the authors?

It looks like we only have CSS now:

      .pp-multiple-authors-layout-inline .pp-author-boxes-name::after{
            content: ",";
        }

**Comment by ojopaul** [comment]
@stevejburge The separator will only work for inline and maybe inline avatar, it won't work for other layout. So, wondering if it won't be confusive if we have an option that's not applying to layouts configuration?

**Comment by ojopaul** [comment]
What's special about inline is because it doesn't have html structure that'll move separator to the next line.

For example, where do you think separator will fit in the below screenshot which is the standard layout?

<img width="1440" alt="Screenshot 2023-06-21 at 09 59 27" src="https://github.com/publishpress/PublishPress-Authors/assets/92122385/34dd8fb8-ec13-4437-a2da-7697df826e4e">

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul If I had to guess: after the "Authors" title

But if we can just get this for the inline options, let's do that

**Comment by ojopaul** [comment]
Read the requirement again, your proposal is text separator for authors like we have the auto `,` for inline layout.

So, why will it be in front of title if it's meant for Authors separator?

**Comment by ojopaul** [comment]
Read the requirement again, your proposal is text separator for authors like we have the auto `,` for inline layout.

So, why will it be in front of title if it's meant for Authors separation (in front of authors name)?

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul Sorry, I was getting mixed up with the other issue about adding a prefix field

I guess a separator would to here with boxes?
<img width="703" alt="Screenshot 2023-06-21 at 9 50 25 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/7dbee17f-04a4-4f0a-b210-ff58a1a5586d">

**Comment by ojopaul** [comment]
@stevejburge 
That's exactly what I mean, doesn't it seems like a not so useful introduction? I'm wondering how a text separator will actually fit in those layouts.

But no problem, I'll add it.

**Comment by stevejburge** [comment]
Thanks @ojopaul Yes, in most cases it won't make sense

My thought is: what's the alternative? Do we restrict what layouts can have it?

**Comment by ojopaul** [comment]
I think I'll just add it if we feel it's a good addition, what tab should this be?

**Comment by stevejburge** [comment]
Yes, that was my thinking

For that reason, I think we should add this. If people don't want, they don't use it

**Comment by ojopaul** [comment]
Maybe it should go beyond text separator to carry other layouts along?
Calling it just "Author Separator" and Allowing html like <hr /> <div> will make it useful for every layouts @stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul Yes please, that's a great idea
