### ISSUE TITLE
Conflict between PublishPress Authors and Yoast SEO

### ISSUE THREAD

**Issue by Kpudlo** [publishpress/PublishPress-Authors#138]
## Expected Behavior
Authors profile picture and name display correctly on the front-end without errors in the back-end.

## Current Behavior
We're having issues with authors on the front end. Our posts are showing the correct author image, but not the correct author name.
https://wdwnt.com/2020/05/photos-new-vintage-pleasure-island-hat-parties-into-disney-springs-2/ 

In addition, according to the WPE error logs, it seems to be there's a conflict with PublishPress Authors.

## Steps to Reproduce (for bugs)
1. Install PublishPress Authors Pro
2. Install Yoast SEO 
3. Write a Post

## Context
Authors are coming up wrong, plus it's slamming the error logs on WPE.

## Your Environment
* Host: WP Engine
* WordPress version:  5.4.1
* PublishPress Authors Pro version: 3.31
* Yoast SEO version: 14.2
* Tested with theme: Zeen
* Link to your project: https://wdwnt.com

**Comment by Kpudlo** [comment]
Yoast SEO Issue Link: https://github.com/Yoast/wordpress-seo/issues/15340

**Comment by stevejburge** [comment]
Thanks @Kpudlo Can you share some of those error logs?

**Comment by Kpudlo** [comment]
Yes! My apologies, I forgot to include it: 
`PHP Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in /nas/content/live/www/wp-includes/formatting.php:4203\nStack trace:\n#0 /nas/content/live/www/wp-includes/formatting.php(4203): str_replace(Array, Array, Object(WP_Error))\n#1 /nas/content/live/www/wp-includes/class-wp-hook.php(287): ent2ncr(Object(WP_Error))\n#2 /nas/content/live/www/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(WP_Error), Array)\n#3 /nas/content/live/www/wp-content/plugins/publishpress-authors-pro/vendor/publishpress/publishpress-authors/src/functions/template-tags.php(62): apply_filters('the_author', Object(WP_Error))\n#4 /nas/content/live/www/wp-content/plugins/publishpress-authors-pro/vendor/publishpress/publishpress-authors/src/modules/yoast-seo-integration/yoast-seo-integration.php(137): get_multiple_authors(0, true, true)\n#5 /nas/content/live/www/wp-includes/class-wp-hook.php(287): MA_Yoast_Seo_Integration->overrideSEOReplacementsForAuthorsPage(Array, Object(stdClass))\n#6 /nas/content/liv in /nas/content/live/www/wp-includes/formatting.php on line 4203`

**Comment by stevejburge** [comment]
thanks @Kpudlo, that's super-helpful

**Comment by nbh707** [comment]
I have found another issue between Yoast and PublishPress Authors (not the pro version). Two of us are adding the content to WordPress but the authors are mostly other people (sometimes multiple authors). The authors pages are correctly rendered in WordPress but the only author pages that exist in the sitemap are me and the other user, I think because somewhere we are being listed as the authors rather than the real authors.

**Comment by andergmartins** [comment]
Thanks @nbh707 for reporting the issue. We have a similar issue opened and we are going to find a fix for it.
