### ISSUE TITLE
Extend Pagination to other layouts

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1381]
Original report: https://wordpress.org/support/topic/authors-list-pagination-not-working/

The user uses this shortcode
[publishpress_authors_list layout="boxed" show_title="no" limit_per_page="20"]

And they have 50 Authors. Pagination should showing.

I confirm this.

However this shortcode works

[publishpress_authors_list layout="authors_recent" limit_per_page="20"]

**Comment by ojopaul** [comment]
@rizaardiyanto1412 The reason authors_recent works is because pagination are only added for `authors_recent` and `authors_index` layout.
