### ISSUE TITLE
Prefix and suffix fields for author box row

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1382]
One user said that they can't add "Written by" for the whole group of authors. That's a good point. We only have a prefix for each author:
<img width="838" alt="Screenshot 2023-06-15 at 4 34 44 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/bf5b2a62-3b03-473f-88b7-3b95e13d66a5">

Could we add prefix and suffixes for each row?

**Comment by ojopaul** [comment]
Same as https://github.com/publishpress/PublishPress-Authors/issues/1379, this will only work for inline layout and not others

**Comment by stevejburge** [comment]
Thanks @ojopaul 

Same question: can we make it available for all layouts, even if it doesn't make sense to use it on all?

**Comment by ojopaul** [comment]
@stevejburge I think the way we can make it useful for all layouts is to allow basic html in the input so they can customise the prefix and suffix as a plus to what they have control over in the layout. So, I'm adding that with the ability.

**Comment by stevejburge** [comment]
@ojopaul Thanks. Thumbs up from me
