### ISSUE TITLE
Conflict with the Advanced Ads plugins

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1398]
> We are adding PublishPress for Authors (and hopefully the entire suite of products) to a large blog and its been smooth except for 1 issue.
> 
> When an author goes to the "mine" view, no posts show. It shows the count but doesnt return any posts.

https://www.loom.com/share/14013296fa6c4ee3aad92af7c8ec0d4c

> The conflict is with the free version of advance ads manager https://wordpress.org/plugins/advanced-ads/
![Screenshot-by-Dropbox-Capture](https://github.com/publishpress/PublishPress-Authors/assets/3868028/2ddb7e7a-bd2c-4ea9-9fbd-2ac2c4be5ec9)

**Comment by mikezielonka** [comment]
Thanks all for fixing that! :)
