### ISSUE TITLE
The property [@type is not recognized by the schema

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1399]
There is typo
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/0a8ea577-327f-4de4-836d-2006b60c7c95)

This is easily replicable on fresh site

Original report: https://wordpress.org/support/topic/newsarticle-schema-error-type-sometimes-appearing-as-type/

**Comment by ojopaul** [comment]
This is fixed but pending release
