### ISSUE TITLE
Allow to select which post type should be displayed in the authors page

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#140]
A user reported it only displays posts. We should provide an option to customize that and select custom post types or pages.
This will probably have effect over the post count as well #95.

**Comment by ellegaarddk** [comment]
I've noticed something, that might be of help. Perhaps...
/wp-admin/edit.php?post_type=page&author=aske-basselbjerg-christensen shows every page
/wp-admin/edit.php?author_name=aske-basselbjerg-christensen&post_type=page show just pages from the chosen author

The difference between author and author_name is significant.

This is just from two different lists elsewhere in the system, but one works, the other doesn't.

**Comment by andergmartins** [comment]
Thanks, @ellegaarddk, we implemented this feature some months ago adding the new setting "Post types to display on the author's profile page:" so I'm closing the issue.
