### ISSUE TITLE
Avatars randomly unassigned on multi-site instance

### ISSUE THREAD

**Issue by c0ntax** [publishpress/PublishPress-Authors#1424]
## Expected Behavior

I have authors that are the 'same' across a multi-site instance. I assign each one an avatar each of them. They use the site to publish stories. Their avatars stay as they are

## Current Behavior

As they work on the site, the avatars on the sites where the site id > 1 slowly start dissapearing. It's not as if they were never assigned, but now they're forced to fallback to a gravatar icon.

Looking in the database reveals that they have an ID for the avatar still set in their termmeta, but it's the id of the uploaded avatar on main site.

I've tried the obvious things of changing the avatar and other bits of information about the author on the site = id:1 and seeing if that messes with their profile on site id > 1 but that didn't do anything. I have no idea what is causing the avatar to be updated.

## Possible Solution

Not sure as I can't find the exact steps to reproduce, but there is certainly an issue around switching sites involved.

## Steps to Reproduce (for bugs)

I'm still trying to track down how it happens. All I know is that over the process of users writing stories, their avatars go. (We're using the block editor rather than classic)

## Context

The problem is that author icons on our stories randomly disappear throughout the day and have to be manually added back in. I'm guessing that switching to using Gravatar will help hide the problem for now.

## Your Environment

* Version used: 4.1.7
* Browser Name and version: Chrome Version 114.0.5735.198 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows

**Comment by stevejburge** [comment]
@c0ntax Thanks for reporting that. Please follow up if you find more. We don't get that many multi-site users so there may be unreported issues like this

**Comment by c0ntax** [comment]
@stevejburge I'm going to close this bug down as it happens to be an issue was caused by the interaction with a different plugin (Plainview Broadcast). Just in case anyone else had this issue and is using that plugin, the problem is this:
When you boardcast a post to another site, it copies across the taxonomy/terms for that post as well, which is how the Authors plugin stores authors. This means that it copies the 'avatar' term meta key with the id from the site it was broadcast from. The quick (and not amazing) solution is to add: `author * avatar` to the protect list in the [term handling config](https://broadcast.plainviewplugins.com/doc/taxonomy-handling/). This will ensure that if you already have an author of the same name on the site you're broadcasting to, it'll not wipe over its config. The downside is that if that author doesn't exist, then it will create it with the wrong avatar id, but you can just update it manually as a one off.

(You can also fix this by writing a plugin in to help with the taxonomy translation, but I'd only bother with this if you have lots of new authors and use avatars, otherwise a manual fix up is fine!)

Sorry for the false report!

**Comment by stevejburge** [comment]
Thanks for the detailed update, @c0ntax 

We've investigated the ability to broadcast content across sites like this and it's tricky. Even duplicating posts with our Revisions plugin is a can of worms. 

I appreciate your help with posting this solution.
