### ISSUE TITLE
Allow users to re-order Author Boxes fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1441]
Can we allow users to change the order of these fields?
<img width="1041" alt="Screenshot 2023-08-15 at 3 42 21 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/6f21e054-3eaa-4396-9180-d32c3086a040">

**Comment by ojopaul** [comment]
It seems I'm ready 2 meanings to this issue
Are you asking to add drag and drop features to "Author Fields" to re-order fields which determine the order by which they show on the Author box editor you're asking to add the drag and drop feature to re-order the field solely on the Author box editor screen?

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul True. I guess both would be useful. We've had requests to control the order of fields in the "Author Profile" and also in the "Author Boxes" area.

**Comment by stevejburge** [comment]
Thanks @ojopaul
