### ISSUE TITLE
Can we allow a limited set of HTML in fields?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1442]
Can we allow users to add a limited HTML choices such as bold, italic and line breaks into fields?

**Comment by ojopaul** [comment]
@stevejburge We can't just be allowing HTML in fields. That's against how those fields are supposed to work.

If user need HTML in a specific field, they should select appropriate field type WYSIWYG Editor

![allow](https://github.com/publishpress/PublishPress-Authors/assets/92122385/46d3c488-ebc1-46a3-afbd-d7cdf2886e9a)
