### ISSUE TITLE
Fix ppma_edit_own_profile capability missing for required role

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1443]
On test sites, I never seem to be able to able to edit the main Administrator account or see the "Author Profile" link

<img width="1430" alt="Screenshot 2023-08-15 at 4 22 58 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/5e8e11c5-cf0b-462a-b3de-b8c3e96bc064">

**Comment by stevejburge** [comment]
Update: I wonder if we have made this too restrictive? I'm testing as an Author and can not see "Author Profile"



<img width="341" alt="Screenshot 2023-08-15 at 4 31 12 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/153aca8e-df14-4d4a-8179-c1f5b32c86b8">

**Comment by stevejburge** [comment]
@ojopaul Here's a new install ...

Administrator:
<img width="590" alt="Screenshot 2023-08-18 at 8 10 18 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/558403c3-6fa2-4793-beb7-d4cf0acf00d2">

Author:
<img width="627" alt="Screenshot 2023-08-18 at 8 10 45 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/97141d3e-ee16-4cda-a43d-6f640c51adb5">

Editor:
<img width="660" alt="Screenshot 2023-08-18 at 8 11 08 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/aee33268-9b88-44e1-b54d-c568608793c5">

Contributor:
<img width="658" alt="Screenshot 2023-08-18 at 8 11 24 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/61a6fef8-7f54-4363-b32f-7cd436e128c9">

**Comment by ojopaul** [comment]
Okay, I'll look into it closely @stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul. The control over who can be an authors is a tricky issue and has my mind thinking this morning ...
