### ISSUE TITLE
Add the Edit links for all Author Fields

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1475]
Having the  Edit / Trash links for some fields but not the others makes this screen hard to navigate:
![Screenshot 2023-09-04 at 8 16 04 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/d0cbd8b3-fc64-4f83-8762-87184d162943)

**Comment by ojopaul** [comment]
@stevejburge If the Trash is removed, how will user be able to delete Fields created by mistake or test purpose?

**Comment by stevejburge** [comment]
@ojopaul They can delete while editing the field

I guess the alternative is to add an "Edit" row for all fields
