### ISSUE TITLE
Custom templates ("Author:Name") do not work with this plugin, it reverts to the default for All Archives

### ISSUE THREAD

**Issue by nelszzp** [publishpress/PublishPress-Authors#1492]
## Expected Behavior

Build a custom template for a specific author, author URL (website.com/author/name) goes to that template

## Current Behavior

If the plugin is active, it instead goes to the default template for All Archives

* Version used: Current
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop 
* Link to your project: https://communityscale.io/author/nels/

**Comment by stevejburge** [comment]
@nelszzp Please share more details. There's not much to go on here.
