### ISSUE TITLE
Email Field Never Dissappears

### ISSUE THREAD

**Issue by Okpara111** [publishpress/PublishPress-Authors#1495]
The email field is always present in the author box even if you disable or delete the field.

**Comment by Okpara111** [comment]
There is no way to remove my review so I just cleared it.

**Comment by stevejburge** [comment]
Thanks, but the 3-star review remains.

**Comment by Okpara111** [comment]
There you go

**Comment by stevejburge** [comment]
Thanks. I appreciate you doing that. Does the attached screenshot help?
<img width="954" alt="Screenshot 2023-10-26 at 4 27 15 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/fc109a76-fc4a-4db2-b74e-97d4bd988871">

**Comment by stevejburge** [comment]
I think I see what happened. Did you try and disable the field here?

If so, I think that counts as a bug. We should probably make it impossible to disable the Email field

<img width="613" alt="Screenshot 2023-10-26 at 4 29 15 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/c4164887-6d56-4c2d-b045-3a0f8521218a">

**Comment by Okpara111** [comment]
It only disappeared on the back-end but remains present on the front-end, I will try uninstalling and installing and try it on different websites, I will get back to you

**Comment by Okpara111** [comment]
After so many tries. I uninstalled and re-installed and it worked like a dream.

**Comment by Okpara111** [comment]
<img width="954" alt="278467571-fc109a76-fc4a-4db2-b74e-97d4bd988871" src="https://github.com/publishpress/PublishPress-Authors/assets/78108405/305dcb66-83af-4b34-8417-e912a1beb31c">
I can't find this setting anymore and the other setting is not getting the job done.

**Comment by stevejburge** [comment]
Thanks @Okpara111. This is on our radar to fix in the next release.

For now, make sure the Email field is enabled.
