### ISSUE TITLE
No message displayed after saving changes on Authors Settings page.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1497]
**Expected results:** Message “Changes saved” appears.
**Actual results:** No message appears.

**Steps to reproduce:** 
1. Login to WordPress site as admin.
2. Under admin menu click “Authors”.
3. Go to “Settings”.
4. Click tab “Author Boxes”.
5. In the drop-down list box choose layout.
6. Click button “Save Changes”.
7. The screen blinked, no message “Changes saved” appears.

OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three

Note: Message “Changes saved” does not appear when making and saving changes under any tab on Authors Settings page.

**Comment by stevejburge** [comment]
This is a fair point. This is what the WordPress core does:

<img width="602" alt="Screenshot 2023-11-01 at 12 11 33 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/180aeeda-6a19-42e7-b359-446b7a7aa44a">
