### ISSUE TITLE
Author boxes are not displayed correctly when using Inline with Avatars layout.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1498]
**Expected results:** Author boxes are displayed correctly when using Inline with Avatars layout.
**Actual results:** Author boxes are not displayed correctly when using Inline with Avatars layout - “bullet point” mark overlays with the author’s name.

**Steps to reproduce:**
1. Login to WordPress site as admin.
2. Under admin menu click Authors.
3. Go to “Settings”.
4. Click tab “Author Boxes”.
5. In the drop-down list box choose Inline with Avatars layout.
6. Click button “Save Changes”.
7. Go to Posts to check changes made.
8. “Bullet point” mark/dot mark before the second author’s avatar overlays with the last letter of the last name of the first author, “bullet point” mark before the second author's avatar overlays with the last letter of the last name of the second author.

OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three

Similar issue was reported before - see #1141.
![3](https://github.com/publishpress/PublishPress-Authors/assets/133815310/25dbee84-a174-4625-a885-75e01a690d62)

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/publishpress/PublishPress-Authors/issues/1499
