### ISSUE TITLE
Author boxes are not displayed correctly when using Inline with Avatars layout – punctuation.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1499]
**Expected results:** There should not be space between the author’s last name and a comma after his last name.
**Actual results:** There is a space between the author’s last name and a comma after his last name.

**Steps to reproduce:**
1. Login to WordPress site as admin.
2. Under admin menu click Authors.
3. Go to “Settings”.
4. Click tab “Author Boxes”.
5. In the drop-down list box choose Inline with Avatars layout.
6. Click button “Save Changes”.
7. Go to Posts to check changes made.
8. There is a space between the author’s last name and a comma after his last name.

OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three

![4](https://github.com/publishpress/PublishPress-Authors/assets/133815310/7f8dd8ad-a848-444b-a8b2-b793e37be494)

**Comment by stevejburge** [comment]
This is the frontend in my testing, in Firefox
<img width="543" alt="Screenshot 2023-11-01 at 12 13 42 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/9ad5083c-92f2-46c2-8b6f-9f768f697d69">
