### ISSUE TITLE
Author boxes are not displayed correctly when using Inline with Avatars layout – space between comma and avatar.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1500]
**Expected results:** There should be space between the comma and author’s avatar.
**Actual results:** There is no space between the comma and author’s avatar.

**Steps to reproduce:**
1. Login to WordPress site as admin.
2. Under admin menu click Authors.
3. Go to “Settings”.
4. Click tab “Author Boxes”.
5. In the drop-down list box choose Inline with Avatars layout.
6. Click button “Save Changes”.
7. Go to Posts to check changes made.
8. There is no space between the comma and author’s avatar.

OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three

![5](https://github.com/publishpress/PublishPress-Authors/assets/133815310/b56814f3-5469-4c18-878b-10ab39571b28)

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/publishpress/PublishPress-Authors/issues/1499
