### ISSUE TITLE
Remove Author Box Meta Field

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1501]
Discussion here:
https://github.com/publishpress/PublishPress-Authors/issues/1495

At some point, we need to clarify "Meta" and "Author Fields". We have 2 completely unrelated "Email fields"

<img width="613" alt="Screenshot 2023-10-26 at 4 29 15 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/0ec29317-997a-4dac-a352-794cd4ec071e">

<img width="627" alt="Screenshot 2023-10-30 at 10 06 49 AM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/ed5f65ff-38b4-4401-8dd3-d3653d75b306">

**Comment by ojopaul** [comment]
@stevejburge You didn't specifically add what changes should be made

**Comment by stevejburge** [comment]
@ojopaul My thinking is that "Show Email field" and "Show Website field" should be retired.

Step #1. 
- Rename "Meta" tab to "View All Posts"
- Remove "Show Email fields" and "Show Website fields" 

Step #2. 
- Configure the Website and Email fields so they match the old Meta fields
<img width="1097" alt="Screenshot 2023-11-06 at 1 09 34 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/96f70baa-d112-4103-94ca-1de23d5b9925">

So this is the old approach:
<img width="508" alt="Screenshot 2023-11-06 at 1 10 11 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/0a2ef730-429a-4801-9016-579e2cc4465e">

This is the new approach:
![Screenshot 2023-11-06 at 1 10 59 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/95774072-4cab-4e16-b920-d98c4d4ba2b8)

**Comment by ojopaul** [comment]
@stevejburge I'm working on this and then realized existing configurations will be affected related to the requirement to make default email and website fields like retired Meta fields. If we change current Website and Email design and configuration, do you know it's going to affect any changes existing user might have made to their Author Box in respective to the fields?

For example, if I've designed my email and link author fields with specific styles and icon, it'll be changes to new design after this update?

**Comment by stevejburge** [comment]
@ojopaul I suspect the number of people affected will be very small.

I wonder if we could leave Meta fields as a "Legacy" option, and disable it for new sites?
