### ISSUE TITLE
"Registered User" instead of "Mapped User"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1503]
Would "Connected User" make more sense to most people?
<img width="493" alt="Screenshot 2023-10-27 at 1 43 55 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/75781507-2dd0-410b-9340-54729a396be1">

**Comment by AnnaShch17** [comment]
Will it work if "Mapped User" will be called "Registered User"?
Thank you.

**Comment by stevejburge** [comment]
Yes, good suggestion. That works too
