### ISSUE TITLE
Make "Support" more visible on the WordPress site.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1509]
It is a suggestion and not a bug.

There is a link “Contact” at the bottom of the “Authors” page that redirects a user to PublishPress Support page. Also, there is a Support option under drop-down menu when you hover over WordPress icon at the top left corner of the site. These two support options are not obvious (visible) right away. 
I think “Contact” sounds more like a link to contact information and not to support page. Should there be a visible Help/Support button anywhere on the page or/and should the “Contact” link be named “Support/Help”?

![Contact](https://github.com/publishpress/PublishPress-Authors/assets/133815310/0cf1b59f-b356-4f1a-92e5-0ed2f62df566)

![Support](https://github.com/publishpress/PublishPress-Authors/assets/133815310/d1ddf999-8d57-4a69-89d3-7816682908bd)

**Comment by stevejburge** [comment]
Thanks @AnnaShch17. Good point. We do need to update that footer on all our plugins.

Hopefully this sidebar shows it:
<img width="346" alt="Screenshot 2023-11-01 at 12 06 07 PM" src="https://github.com/publishpress/PublishPress-Authors/assets/3868028/c4c4890e-bcc1-489d-9d8e-249729a65ed5">
