### ISSUE TITLE
Author's page' do not reflect layouts saved in settings ('Boxed' layout displays in default).

### ISSUE THREAD

**Issue by KatKKat** [publishpress/PublishPress-Authors#1532]
### Steps to Reproduce
Pre-condition: Custom Author Box Layout created -  named ' My New Box'. Posts are created.

1. Log in to WordPress as admin.
2. Navigate to 'Authors' -> 'Settings->'Author Boxes' tab
3. Select the "My New Box" layout option-> Click 'Save Changes' button
4. Navigate to the website-> open the post
5. Scroll down to Author's boxes -> NOTE ' My New Box' layout was successfully applied (Attachment 2)
6. Click on author's name hyperlink
7. 'Author's page opens
NOTE: 'Boxed' layout displayed instead of custom ' My New Box' layout (Attachment 3)

### Environment
Version used: Authors 4.2.1
Browser Name and version: Google Chrome
Operating System and version (desktop or mobile): MaсOs Monterey, version 12.6.7
Attachment 1
![Authors page](https://github.com/publishpress/PublishPress-Authors/assets/71658656/d962be2b-5384-4b6a-b81a-4b62021d548a)
Attachment 2
<img width="712" alt="Screen Shot 2023-11-07 at 17 31 28" src="https://github.com/publishpress/PublishPress-Authors/assets/71658656/c51af65d-1d8f-4193-a122-3b127b37d299">
Attachment 3
<img width="1370" alt="Screen Shot 2023-11-07 at 16 35 49" src="https://github.com/publishpress/PublishPress-Authors/assets/71658656/072b732a-cf19-4bcd-aeba-ae79d9349f98">

**Comment by ojopaul** [comment]
@stevejburge Can you confirm this issue?

**Comment by stevejburge** [comment]
@ojopaul It's OK. We can skip this one
