### ISSUE TITLE
PHP 8.2 Deprecated notice

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1533]
> Deprecated: Creation of dynamic property PublishPress\Future\Framework\WordPress\Facade\NoticeFacade::$hooks is deprecated in /home/javunemoxo2373/web/yucky-yak-jkkwe.instawp.xyz/public_html/wp-content/plugins/post-expirator/src/Framework/WordPress/Facade/NoticeFacade.php on line 14
> 
> Deprecated: Creation of dynamic property MA_Yoast_Seo_Integration::$module_url is deprecated in /home/javunemoxo2373/web/yucky-yak-jkkwe.instawp.xyz/public_html/wp-content/plugins/publishpress-authors/src/modules/yoast-seo-integration/yoast-seo-integration.php on line 48
> 
> Deprecated: Creation of dynamic property MultipleAuthors\Classes\Legacy\LegacyPlugin::$yoast_seo_integration is deprecated in /home/javunemoxo2373/web/yucky-yak-jkkwe.instawp.xyz/public_html/wp-content/plugins/publishpress-authors/src/core/Classes/Legacy/LegacyPlugin.php on line 140

![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/9ed00048-53d3-4d4e-9f74-70437b1c3980)

This deprecated notice show up on 8.2

**Comment by neverything** [comment]
There are additional deprecation warnings for other integrations:

<img width="1936" alt="Screenshot 2024-01-08 at 18 03 04" src="https://github.com/publishpress/PublishPress-Authors/assets/368120/480b35bf-64ac-45f6-8579-a6900bc9c904">

Let me know if I can help with a pull request?

**Comment by emalquier** [comment]
Hi. 
I still have this bug on my blog when upgrading from 7.4 to 8.3, and on all pages, not just on the backoffice.
I downgraded to 8.1 and indeed it works again, so it's a 8.2 and/or 8.3 problem?
Reported here for more: https://wordpress.org/support/topic/deprecated-creation-of-dynamic-property-22/#post-17870640
