### ISSUE TITLE
Turning off 'Biographical info' from Authors page remove Author box entirely

### ISSUE THREAD

**Issue by KatKKat** [publishpress/PublishPress-Authors#1562]
### Steps to Reproduce 
Pre-condition: Author with biographical info is created. Biographical info enabled. Attachment 1
1. Log in to WordPress as admin.
2. Navigate to 'Authors' -> 'Settings->'Author Pages' tab
3. Uncheck 'Show author bio:' -> 'Save Changes'
4. Navigate to 'Authors page'
Note: Authors box does not display Attachment 1, 2

### Environment
Version used: Authors 4.2.1
Browser Name and version: Google Chrome
Operating System and version (desktop or mobile): MaсOs Monterey, version 12.6.7
Attachment 1
<img width="1407" alt="Screen Shot 2023-11-28 at 20 17 44" src="https://github.com/publishpress/PublishPress-Authors/assets/71658656/185917dc-aa11-4146-b320-00e9c9860bd7">
Attachment 2
<img width="1399" alt="Screen Shot 2023-11-28 at 20 18 48" src="https://github.com/publishpress/PublishPress-Authors/assets/71658656/80c1ec51-14a6-4c2c-af0d-bb2b937f628d">
Attachment 3
![Nov-28-2023 20-13-39](https://github.com/publishpress/PublishPress-Authors/assets/71658656/f4375509-f036-4656-a21c-02fbda28acdb)

**Comment by ojopaul** [comment]
@stevejburge Maybe the wording is wrong for the description?

The Show Author Bio is meant to show Author box on the page and not description. Author box description is controlled in Author Box settings and this setting is for the Author page.

Maybe you can suggest a title change for the setting but it's currently working as designed.
