### ISSUE TITLE
No warning message displayed when search field on “Author Fields” page is left blank.

### ISSUE THREAD

**Issue by AnnaShch17** [publishpress/PublishPress-Authors#1568]
**Expected results:** A warning message "Cannot leave search field blank" appears.
**Actual results:** No warning message appears.

**Steps to reproduce:**

1. Login to WordPress site as admin.
2. Under admin menu, click “Authors”, then click “Author Fields”.
3. “Author Fields” page opens.
4. Leave the search field blank.
5. Click button “Search Author Fields”.
6. No warning message appears.

Note: this issue is similar to issues #1521 and 1565.
OS – Windows 11, browser – Google Chrome, WordPress version 6.3.2, Theme – Twenty Twenty-Three.

**Comment by stevejburge** [comment]
This is the default WordPress behavior
