### ISSUE TITLE
Preview authors on a post

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1571]
Could we add a different preview option to show the authors on a post?

This would be the preview option for "Author Categories" boxes

![Screenshot 2023-12-05 at 1 41 07 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/2cd66592-7b24-4eda-96fc-5aea6845a11a)

**Comment by ojopaul** [comment]
Fixed by replacing preview author with preview post instead of having the 2
