### ISSUE TITLE
Some displays are falling out of the post 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1577]
This is the List Author Categ
![Screenshot 2023-12-05 at 3 16 04 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/2ffebe1e-14be-4206-a546-b5353e37d21e)
ory Block layout:

It floats all the way to the left of the screen with the Twenty Twenty-Four theme. The boxed layout don't have this problem
![Screenshot 2023-12-05 at 3 12 00 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/88949195-b816-4912-9d42-22dead33a650)

**Comment by ojopaul** [comment]
Fixed
