### ISSUE TITLE
Missing comma after final author

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1578]
In this layout, there is a comma after each author, then no comma after the final author

![Screenshot 2023-12-05 at 3 27 11 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/fd6c0579-fdc3-4508-813c-62e1ee8c9ba2)

**Comment by ojopaul** [comment]
@stevejburge Comma is the separator and why should it be after the last author?

In this case, maybe the separator shouldn't be use and simply be remove in the layout tab but for other cases that simply lists the authors, it won't make sense to add the separator to the last author when there's no users again.

**Comment by stevejburge** [comment]
Thanks @ojopaul. Yes, perhaps the solution is to only use the separator if there is a following author

**Comment by ojopaul** [comment]
Can you do this
- remove Group prefixes and Suffixes
- Hide group title and send screenshot of what the page look like so I can
use that explain why you have that comma?

**Comment by ojopaul** [comment]
I believe the comma is coming from Box Layout > Author Separator and in this case Separator cannot be added to the last user. Reopen after my new update if the comma is still there after removing the separator
