### ISSUE TITLE
Author Box doesn't go back to default

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1580]
- Choose a new layout in "Author Category Layout"
- Go back to Default

![Screenshot 2023-12-05 at 9 20 58 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/e785c8ba-6eb8-437b-ad0a-58b51fb1cf53)

The layout does not go back to Default
![Screenshot 2023-12-05 at 9 21 17 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/ceba6409-632e-4fff-854a-2de8253debaf)

**Comment by ojopaul** [comment]
I think there's a misunderstanding on that. That default implies not selecting anything since the first option will always be selected by default for a dropdown select if there's no empty placeholder.

Should i simply rename it to "None" or "Select Layout"? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Yes, something like "Default Layout" would work.

However, I think the original problem persists. If you enable "Enable Author Grouping" and then disable it, things don't go back to normal.

**Comment by ojopaul** [comment]
That's why there's the warning, when you select a layout, the author boxes
settings are updated.

**Comment by stevejburge** [comment]
Ah, interesting. This will require a little thinking. 

I'm sure some people will try to test this option and not realize they'll lose their settings.

**Comment by stevejburge** [comment]
Closing in favor of a bigger solution
