### ISSUE TITLE
New Pro feature: Author Categories Boxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1582]
Can we consider creating new Author Categories Boxes for Pro users?

New button:
![Screenshot 2023-12-06 at 9 46 16 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/11d57922-fd53-4600-a715-773dc547e8a9)

New column:
![Screenshot 2023-12-06 at 9 46 31 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/7ba50ac6-aa34-449a-a697-24a283309876)

Far fewer settings:
![Screenshot 2023-12-06 at 9 52 07 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/a56c5d5a-4dc5-4dbc-8e65-4e05e7a0f84c)

**Comment by ojopaul** [comment]
Fixed
