### ISSUE TITLE
"Coauthor" instead of "Co Author"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1590]
Just a small thing, but let's use "Coauthor" instead of "Co Author"

https://www.merriam-webster.com/dictionary/coauthor
![Screenshot 2023-12-20 at 9 54 01 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/3acc7a6e-278a-49b1-917e-b5b754493b9a)

**Comment by ojopaul** [comment]
Fixed
