### ISSUE TITLE
Author Boxes screen isn't fully responsive

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1594]
![Screenshot 2023-12-21 at 1 17 59 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/0dd9ba34-2707-469e-aa1b-d2867785a2f7)

**Comment by ojopaul** [comment]
@stevejburge I think you added wrong image

**Comment by stevejburge** [comment]
@ojopaul sorry, here we go:
![Screenshot 2024-01-03 at 8 48 27 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/0091341e-a97d-40aa-b227-b894aa97011b)
