### ISSUE TITLE
Add user_id and term_id parameter to [publishpress_authors_box] shortcode

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1602]
It will be good if we have authors id parameter so user can show authors box based on the authors id

Original request: https://wordpress.org/support/topic/pulling-specific-authors/

**Comment by ojopaul** [comment]
Fixed in https://github.com/publishpress/PublishPress-Authors/pull/1586/commits/7680d0b26872ab9408bd517c59d9d44139fd0473
