### ISSUE TITLE
Change button order for Author Categories

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1605]
![Screenshot 2024-01-08 at 10 18 07 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/a1e065d1-0a9f-4b16-896e-4f610bb22d53)

**Comment by stevejburge** [comment]
Or we perhaps change the order? This is the WordPress default:
![Screenshot 2024-01-08 at 10 18 47 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/aa2a9d03-2b8a-4c5e-8ebd-5c41cb9bae55)

**Comment by ojopaul** [comment]
Changing the Order is better as removing it means user has to reload the page if they change their mind from making the edit after typing. @stevejburge

**Comment by stevejburge** [comment]
Sure thing. Let's do that
