### ISSUE TITLE
New column for "Authors"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1681]
Should we add a 4th column? Or maybe remove the email address to make room?

Existing User
Guest Author With User Account
Guest Author With No Account

![Screenshot 2024-03-01 at 11 37 26 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/a766f4fb-89f1-4861-bfde-8d80b420da3d)

**Comment by ojopaul** [comment]
@stevejburge We should be able to add new column without removing email column but what'll be the column title?

**Comment by stevejburge** [comment]
"Author Type"
