### ISSUE TITLE
Tooltip or explanation for schema

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1682]
How can we explain this for users?

![Screenshot 2024-03-01 at 12 10 49 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/4a8e38ae-01a2-4530-854a-c6e4839fb4d7)

**Comment by ojopaul** [comment]
I don't think a quick edit should have too many text especially when the explanation texts will be same thing seen on the form which is literally by the left side and it's like simply duplicating the text.

Or is the explanation text not showing in your form?

**Comment by stevejburge** [comment]
Fair point. I wonder if I need to write a documentation article we can link to. We can tell people what the options are

**Comment by ojopaul** [comment]
@stevejburge I already notified @rizaardiyanto1412 on slack channel last week. Maybe we could add link the documentation when ready.

**Comment by stevejburge** [comment]
Let's use this link https://publishpress.com/knowledge-base/author-categories-schema/
