### ISSUE TITLE
Final decision on text for user types

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1688]
This is my fault. I feel like these labels aren't 100% clear yet:

- Existing User
- New User
- Guest Author

![Screenshot 2024-03-04 at 10 48 50 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/25b8a98b-8e6d-4281-a1a2-693df6c75cb4)

**Comment by stevejburge** [comment]
Some ideas. Can we do two lines for the tabs?

- Registered User? Connected User? 

- Guest Author With User Account

- Guest Author With No User Account

**Comment by ojopaul** [comment]
@stevejburge Can you separate this issue?

**Comment by stevejburge** [comment]
@ojopaul I guess this is all one issue? Could we use the labels above but push them to 2 rows?
![Screenshot 2024-03-04 at 11 00 10 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/f9f1c2c4-34d4-4aff-90ff-e672f61a9c64)

**Comment by ojopaul** [comment]
One is talking about the new Author form and another is talking about the author list table.

Also in personal opinion, having those title look confusing unless we're really sure.

I don't see reasons the choice shouldn't be as simple as possible.

**Comment by stevejburge** [comment]
Yes, simple is always good

However, I'm also try to find a solution that is:
- Clear
- Consistent between the left sidebar and the table on the right
