### ISSUE TITLE
Authors are not working for WooCommerce products

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#169]
WooCommerce's product doesn't support authors so Multiple Authors won't display the authors field.

**Comment by stevejburge** [comment]
@andergmartins This may help? https://publishpress.com/blog/add-authors-woocommerce-products/

**Comment by andergmartins** [comment]
@stevejburge yes, thanks, but the user reported it wasn't working even using that 3rd party plugin. But I think I have a fix
