### ISSUE TITLE
Custom Author Box Produce Errors

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1691]
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/56938ef1-d5dc-4ac2-801b-c3fed6babae4)

Step to replicate:
1. Enable LinkedIn Field 
2. Generate theme template for author boxes
3. Copy generated code, add it to your theme
4. Select custom author box in the settings

It will show this error:
`Notice: Undefined variable: key in /Users/rizaardiyanto/Local Sites/ppro/app/public/wp-content/themes/astra/publishpress-authors/author-boxes/x.php on line 83

Notice: Uninitialized string offset: 0 in /Users/rizaardiyanto/Local Sites/ppro/app/public/wp-content/plugins/publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/core/Classes/Objects/Author.php on line 430

Warning: trim() expects parameter 1 to be string, array given in /Users/rizaardiyanto/Local Sites/ppro/app/public/wp-content/themes/astra/publishpress-authors/author-boxes/x.php on line 83`

**Comment by stevejburge** [comment]
@rizaardiyanto1412 @ojopaul I can re-create this
![Screenshot 2024-04-02 at 12 53 36 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/f3b6fa5e-c10f-44d0-a653-a29a1adc00b2)


![Screenshot 2024-04-02 at 12 54 22 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/40ac2e34-d28c-4613-ace5-b2d8c48c573b)
