### ISSUE TITLE
Add a setting to choose which Author types are allowed

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1692]
Let's add a setting to allow admins to disable some of these:
![Screenshot 2024-03-06 at 7 56 47 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/8cb3fb8d-5cd1-44a6-854d-c904f677db70)

**Comment by stevejburge** [comment]
Related https://github.com/publishpress/PublishPress-Authors/issues/1703

**Comment by ojopaul** [comment]
Enable the 3 options for old site and only 2 options for new installation disabling the "Guest Author With No User Account" by default.
