### ISSUE TITLE
filter_count_author_posts returns wrong post count

### ISSUE THREAD

**Issue by SabrinaCP** [publishpress/PublishPress-Authors#17]
Hi, 
we already had a problem with a prior version of the plugin (see https://github.com/publishpress/PublishPress/issues/250).
Now I just updated to Multiple Authors Version 3.1.0. The function `filter_count_author_posts` is now located somewhere else, but the problem is still the same:

``` AND tr.`term_taxonomy_id` = {$term_id}"``` (https://github.com/publishpress/PublishPress-Authors/blob/development/core/Plugin.php#L805)

The query contains a comparison between two different things: the **term_taxonomy_id** and the **term_id**. But these ids are not necessary the same. I know, very often they are just the same, but not when you have a more complicated term structure (like we have). So in this cases it returns the wrong post count.

Greetings,
Sabrina

**Comment by andergmartins** [comment]
Hi @SabrinaCP ,

Thank you for the details. Good catch. I will work on a fix to make sure we are comparing the ID with the correct field in in the query.

**Comment by andergmartins** [comment]
@SabrinaCP please, could you try the [3.2.1-beta.1](https://github.com/publishpress/PublishPress-Authors/releases/tag/3.2.1-beta.1)?
