### ISSUE TITLE
New designs for Author Boxes

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1718]
Let's add more default boxes ... more layouts that don't require set-up

Riza has some here: https://publishpress.com/knowledge-base/custom-template-for-author-category-boxes/

He took some ideas from here: https://github.com/publishpress/PublishPress-Authors/issues/58

**Comment by stevejburge** [comment]
Here's one idea with a right-aligned image:
![Screenshot 2024-04-22 at 12 32 47 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/b6595b1f-527f-4cd4-914b-d87aa2e4319f)

**Comment by ojopaul** [comment]
I'm closing this issue after separating the 3 new author box into different issues https://github.com/publishpress/PublishPress-Authors/issues/1736
https://github.com/publishpress/PublishPress-Authors/issues/1737
https://github.com/publishpress/PublishPress-Authors/issues/1738
