### ISSUE TITLE
Add default Job Title field

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1725]
Can we add a default "Job Title" field to make it easier to create boxes like this:
![Screenshot 2024-04-22 at 12 51 57 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/49cdc9b9-ec78-4519-a338-d19f80ae6904)

**Comment by ojopaul** [comment]
@stevejburge Shouldn't that be coming from Author Field? We already have too many tabs already making author box not easy to configure or what do you mean by adding Job Title Field to author box?

**Comment by stevejburge** [comment]
I think this is an important field that many sites need

First Name
Last Name
Bio
Job Title 
Facebook
Twitter etc.

**Comment by ojopaul** [comment]
Should this field be added to both free and pro or pro only? @stevejburge

**Comment by stevejburge** [comment]
Let's say Free also, please
