### ISSUE TITLE
Update promo box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1727]
Can we include this box on a lot more screens in the Free version?
Can we also add "Support for Polylang"?

![Screenshot 2024-04-24 at 12 57 55 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/5d69dc24-462a-4e36-96af-49bb63f6a0f2)

**Comment by ojopaul** [comment]
@stevejburge We have the promo sidebar and almost all the screens that could contain them, what screen do you think they are our screen and fit in but missing?

**Comment by stevejburge** [comment]
@ojopaul You're right. Maybe just the Author Edit screen, please

![Screenshot 2024-04-25 at 10 36 44 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/747b474e-47ee-4d32-97e1-1e2b90dde388)

**Comment by ojopaul** [comment]
@stevejburge It's impossible to add to that screen. It's a WordPress tag template page we don't have access to the change the structure or modify the template

**Comment by stevejburge** [comment]
Ok, thanks. We can close this then.
