### ISSUE TITLE
Add Author box icon search

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1771]
I wonder if there are ways we can make it easier to add icons?

- Could we add a search box, perhaps?
- Could Font Awesome be enabled by default?

![mastodon-customize](https://github.com/publishpress/PublishPress-Authors/assets/3868028/8c34119e-eae3-4065-9529-ec08db01b293)

**Comment by ojopaul** [comment]
As it stand, the only option aside linking to the source is loading all the icons so they can search or select.

For Font Awesome been enabled by default, I think we already discuss this but can't remember what our conclusion was that made it not a good idea to enable it but if it keep coming back to request list, then we should just do it then and then pick up the issue that comes in report with conflict etc @stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul. I think this is worth a try. We could retain the setting to disable this feature.
