### ISSUE TITLE
Use PublishPress Purple color for top banner

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1787]
![Screenshot 2024-05-28 at 10 35 17 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/572072b5-caf6-48c2-b64a-95eb9c3eb174)

**Comment by ojopaul** [comment]
This happens when taxopress is activated because it's overriding the color.

**Comment by stevejburge** [comment]
Makes sense, thanks @ojopaul
