### ISSUE TITLE
Update Author Box text labels

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1795]
This is related to https://github.com/publishpress/PublishPress-Authors/issues/1794

- Should be "Box Title"?
- What does "Size" refer to?
- I think "Color" may need updating here and in other areas such as "Display Name", "Biographical Info" and "Box Layout"

![Screenshot 2024-05-31 at 9 45 06 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/a1e8a1c8-cf83-4941-9035-f83b90d133ac)

**Comment by ojopaul** [comment]
@stevejburge Do you mean for example, we should update them to Box Title Color, Box Title Size etc?

**Comment by stevejburge** [comment]
Yes, please. A lot of the labels are not specific.
