### ISSUE TITLE
Add redirect for new installs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1796]
We should redirect new users to the "Authors" screen

https://make.wordpress.org/core/2024/05/24/wordpress-6-5-4-an-upcoming-maintenance-release/
![Screenshot 2024-05-31 at 5 52 24 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/7e970027-5227-4f8a-bae6-3d5e5ccc4322)

**Comment by ojopaul** [comment]
@stevejburge Is there any reason this should be for WordPress 6.5.4 alone, what if a site on old version is installing Authors for the first time?

**Comment by stevejburge** [comment]
Sorry, it doesn't have to be specific to 6.5.4 but the ability to do redirects was broken before that update
