### ISSUE TITLE
Integration with Polylang

### ISSUE THREAD

**Issue by johnbillion** [publishpress/PublishPress-Authors#18]
It appears that when this plugin is installed on a site that uses Polylang, author archive URLs don't work. Browsing an author archive (`example.com/fr/author/john`) returns no results.

Is this something you can take a look at?

**Comment by stevejburge** [comment]
Thanks @johnbillion Sure thing. We normally test our plugins with WPML but should add Polylang too.

I don't see anything in the error logs, but I do see the "no results" problem.

**Comment by seidenfaden** [comment]
What happened to this one? 

The issue persists.

**Comment by andergmartins** [comment]
@seidenfaden we are working on it again

**Comment by andergmartins** [comment]
@johnbillion, @seidenfaden we have a new alpha package addressing this bug, but it will be released probably next week.

[publishpress-authors-3.13.1-hotfix-18-polylang.zip](https://github.com/publishpress/PublishPress-Authors/files/6367726/publishpress-authors-3.13.1-hotfix-18-polylang.zip)
