### ISSUE TITLE
Guest Author not showing on Latest Post widget

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1812]
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/f4e4d0f1-4902-46e1-a8b5-2a15c44b67e7)
![image](https://github.com/publishpress/PublishPress-Authors/assets/83811723/3602fe3b-24ee-4faa-931b-aa0bb88ce8ba)

Guest author with no user account is not showing correctly in latest post widget

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Does this happen if the Guest Author has a user account?

**Comment by rizaardiyanto1412** [comment]
@stevejburge It works fine with guest author that has a user account

**Comment by stevejburge** [comment]
@rizaardiyanto1412 That's the expected result. Authors with no user account won't show on displays like that
