### ISSUE TITLE
Make Preview the first tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1816]
The Preview option is great. Let's make it the first tab
![Screenshot 2024-06-14 at 12 05 56 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/03e229fd-f2c9-49a9-bcde-d8a8d94a3619)

**Comment by ojopaul** [comment]
@stevejburge Do you mean we should make it default tab? Making it first tab means it comes before all other tabs like general etc.

So, first or default tab?

**Comment by stevejburge** [comment]
@ojopaul Yes, please - the first tab and the default tab
