### ISSUE TITLE
Use tabbed layout for Author Pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1819]
- Could we consider a tabbed layout for Author Pages, similar to Authors?
- Could we include a preview, or perhaps a link to a preview?

![Screenshot 2024-06-14 at 12 12 43 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/391c1ddd-cfe0-4115-8a28-fe48f339226e)

**Comment by ojopaul** [comment]
@stevejburge Do you have suggestion for how the settings should be grouped to tabs?

**Comment by stevejburge** [comment]
Layout
![Screenshot 2024-06-17 at 10 28 30 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/e8ff648f-e996-45eb-b126-5f69d97b4de1)

Author Bio
![Screenshot 2024-06-17 at 10 29 07 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/8114f0e3-e96a-459a-810a-6af22b5babd9)

Author Page Title
![Screenshot 2024-06-17 at 10 29 32 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/320aba79-7f6e-4887-b573-48af822a7dce)

Posts
![Screenshot 2024-06-17 at 10 29 54 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/9cbdaf92-6e25-4882-b83c-d7de6e309da3)

**Comment by ojopaul** [comment]
@stevejburge So, we put "Enable author pages" in a single and first tab General?

**Comment by stevejburge** [comment]
Sure, let's do that. 

- We can also add a description: "Please note this feature will not work for all themes."
- We can add a preview link, perhaps to the site admin or the current user
