### ISSUE TITLE
Make some Author List features Pro-only

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1820]
Could we consider making some features such as "Options" and "Search" into Pro-only features?
![Screenshot 2024-06-14 at 12 16 41 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/91a51611-aebb-4564-b1a0-1d6a7b0531fe)

**Comment by ojopaul** [comment]
What method should we use here? 
1. Remove the tab contents and show texts/promo texts to let user know it's a pro feature like TaxoPress
2. Show preview of the fields so user knows the fields available in the pro version? @stevejburge

**Comment by stevejburge** [comment]
Let's go with #1 and use the TaxoPress approach please
