### ISSUE TITLE
Author List spacing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1836]
![Screenshot 2024-06-20 at 9 24 07 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/c638b8be-14e8-4fe0-92bd-f0c085ff66f7)

**Comment by ojopaul** [comment]
@stevejburge Does it look the same in frontend?

**Comment by stevejburge** [comment]
Not exactly, but it could use more spacing on the frontend too
![Uploading Screenshot 2024-06-20 at 9.30.56 AM.png…]()

**Comment by ojopaul** [comment]
@stevejburge That's the reason I put the preview notice test.

**Comment by stevejburge** [comment]
Understood. Can we add a little more front end spacing?

**Comment by ojopaul** [comment]
Unless we want to move the preview to full page or open it in frontend. Otherwise, we can't expect same result

**Comment by stevejburge** [comment]
Sure. Let’s ignore the preview for now

Can we add a little extra column spacing for the front end view?

**Comment by ojopaul** [comment]
@stevejburge Can you upload your screenshot again, seems the upload failed?

**Comment by stevejburge** [comment]
![Screenshot 2024-06-20 at 9 30 56 AM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/9d9e114b-6985-4ab4-9f06-cb2f84d919ca)
