### ISSUE TITLE
Add documentation link for Author Pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1843]
Let's work on some advice for the Author Pages feature. How do people avoid the redirect error?

Is it as simple as saving the "Permalinks" settings?

![Screenshot 2024-06-20 at 4 33 08 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/2ebb7a6d-d071-47c2-adec-9d914a2cb383)

**Comment by ojopaul** [comment]
I haven't experience this before but it should be due to permalink. Does saving the permalink fix the issue for you? @stevejburge

**Comment by stevejburge** [comment]
Yes, that fixed it in for me on several sites.

Maybe the best solution is a documentation link; "This feature may not work with all themes. Click here for more details."

I can create a link for "Click here for more details" at https://publishpress.com/knowledge-base/author-pages-troubleshooting/
