### ISSUE TITLE
Add Trash feature to Authors Lists

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1848]
Can we use "Trash" and not "Delete" for Authors Lists. This matches the rest of the plugin
![Screenshot 2024-06-20 at 5 26 12 PM](https://github.com/publishpress/PublishPress-Authors/assets/3868028/38d50d40-d4a1-4893-8f94-7556488f14ca)

**Comment by ojopaul** [comment]
@stevejburge Do you mean change the text to trash while the post is actually deleted or change it to trash so it can be permanently deleted on another screen?

**Comment by stevejburge** [comment]
change it to trash so it can be permanently deleted on another screen
