### ISSUE TITLE
Deprecated Message on PHP 8.3

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1858]
Deprecated: Creation of dynamic property MA_Author_List::$module_url is deprecated in /sites/maitronweb/www/web_main/wp-content/plugins/publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/modules/author-list/author-list.php on line 50

Deprecated: Creation of dynamic property MA_Author_List::$module is deprecated in /sites/maitronweb/www/web_main/wp-content/plugins/publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/modules/author-list/author-list.php on line 82

Deprecated: Creation of dynamic property MA_Author_Pages::$module_url is deprecated in /sites/maitronweb/www/web_main/wp-content/plugins/publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/modules/author-pages/author-pages.php on line 50

Deprecated: Creation of dynamic property MA_Author_Pages::$module is deprecated in /sites/maitronweb/www/web_main/wp-content/plugins/publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/modules/author-pages/author-pages.php on line 80

Can we fix the deprecated message?

**Comment by ojopaul** [comment]
https://github.com/publishpress/PublishPress-Authors/issues/1852
