### ISSUE TITLE
Plugin::filter_user_has_cap() should use the passed in user object, not the current user

### ISSUE THREAD

**Issue by johnbillion** [publishpress/PublishPress-Authors#186]
## Expected Behavior

The `Plugin::filter_user_has_cap()` should use the contextual parameters passed into it, so that the `user_can()` function works as expected.

## Current Behavior

This method calls `wp_get_current_user()`, which is not necessarily the correct user for the current capability check. This can introduce unexpected behaviour when the `user_can()` function is used to check a capability of a user _other than the current user_.

## Possible Solution

There is a fourth parameter passed to filters that attach to the `user_has_cap` hook. This fourth parameter contains the user object for the user whose capabilities are being checked. This parameter should be added to the method, and can then be used thus:

```diff
- $current_user = wp_get_current_user();
+ $current_user = $user;
```

**Comment by stevejburge** [comment]
Thanks so much for all your useful feedback today @johnbillion
