### ISSUE TITLE
Use Alt text on Avatar Author Box

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1880]
Avatar on Author box is using the author name instead of the alt text. Lets change it to alt text

From client:

Currently, when PublishPress Authors shows an avatar, it uses the author's name as ALT text. This is resulting in an accessibility issue, since the alt text matches the text next to it.

The avatars I'm using are all images in the media library, and they all have ALT text there (e.g. "a person in a blue short").
Is it possible to just have the code output that alt text?

https://secure.helpscout.net/conversation/2664369908/224624?viewId=6932143

**Comment by stevejburge** [comment]
Possibly. This one needs some thought
