### ISSUE TITLE
Deprecated: Creation of dynamic property MA_Author_Pages

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1883]
Deprecated: Creation of dynamic property MA_Author_Pages::$module_url is deprecated in /home/shokalshondha/public_html/wp-content/plugins/publishpress-authors/src/modules/author-pages/author-pages.php on line 50

Deprecated: Creation of dynamic property MA_Author_Pages::$module is deprecated in /home/shokalshondha/public_html/wp-content/plugins/publishpress-authors/src/modules/author-pages/author-pages.php on line 80

PHP 8.2

**Comment by ojopaul** [comment]
Fixed on related issue https://github.com/publishpress/PublishPress-Authors/issues/1946
