### ISSUE TITLE
Group the color settings together

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#1888]
This is closely related https://github.com/publishpress/PublishPress-Authors/issues/1794

The text color and background color should be next to each other
![Screenshot 2024-08-15 at 12 19 48 PM](https://github.com/user-attachments/assets/9200adaa-4625-4236-96ba-e85c0916ae48)

**Comment by ojopaul** [comment]
@stevejburge Those fields are not the same or apply to same element. The background color is for the icon and icon fields are grouped together

**Comment by stevejburge** [comment]
Ok, thanks @ojopaul. Let's close this in favor of the other issue which attempts to provide sub-headings and organize these settings
