### ISSUE TITLE
Schema Issue with RankMath

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1901]
Original report: https://secure.helpscout.net/conversation/2700707337/225602?viewId=6932143

Step to replicate:
1. Install RankMath
2. Set article type to NewsArticle

![image](https://github.com/user-attachments/assets/6ee0c3f3-3af1-4f8f-8f5c-85be3be03cd4)

When PublishPress Authors active, you will get this scheme
[schema issue.txt](https://github.com/user-attachments/files/16947558/schema.issue.txt)

When PublishPress Authors deactivated, you will get correct schema:
[correct schema.txt](https://github.com/user-attachments/files/16947563/correct.schema.txt)

The difference?

WRONG:
![image](https://github.com/user-attachments/assets/51ad7fe1-1fb2-403b-9510-e8366aa1dac3)

CORRECT:
![image](https://github.com/user-attachments/assets/dd43b7b1-58b3-44c9-a593-946e1630145b)

From client:

> Found the line code with the issue, removed the function, and it's working correctly.
> 
> publishpress-authors-pro/lib/vendor/publishpress/publishpress-authors/src/modules/rank-math-seo-integration/rank-math-seo-integration.php
> 
> if (isset($data['publisher'])) {
> $data_publisher = $data['publisher'];
> if (isset($author_profile_data['@name'])) {
> $data_publisher['name'] = $author_profile_data['@name'];
> } elseif (isset($author_profile_data['name'])) {
> $data_publisher['name'] = $author_profile_data['name'];
> }
> if (isset($author_profile_data['sameAs'])) {
> $data_publisher['sameAs'] = $author_profile_data['sameAs'];
> }
> 
> if (isset($author_profile_data['@image'])) {
> if (isset($data_publisher['image'])) {
> $data_publisher['image'] = $author_profile_data['@image'];
> } elseif (isset($data_publisher['logo'])) {
> $data_publisher['logo'] = $author_profile_data['@image'];
> }
> } elseif (isset($author_profile_data['image'])) {
> if (isset($data_publisher['image'])) {
> $data_publisher['image'] = $author_profile_data['image'];
> } elseif (isset($data_publisher['logo'])) {
> $data_publisher['logo'] = $author_profile_data['image'];
> }
> }
> $data['publisher'] = $data_publisher;
> }

**Comment by ojopaul** [comment]
**I'm adding this note for future reference**

> The reason for that replacement is to replace Guest Author name, and also have correct name incase of multiple authors.
> 
> I'll take the issue as "do not replace the Publisher name if the article type is NewsArticle".
> 
> I also believe what @rizaardiyanto1412 mean by "...You'll get the correct schema" is getting publisher name that's not the post article author since this issue is not about wrong Author name but publisher not neccesarily been the Author.
