### ISSUE TITLE
4.7.0 introduced a slow query from avatar alt text, Add option to filter avatar alt

### ISSUE THREAD

**Issue by c0ntax** [publishpress/PublishPress-Authors#1923]
## Expected Behavior

When displaying a post with an author's custom avatar, the code to generate the page should be performant

## Current Behavior

`get_custom_avatar()` now uses `attachment_url_to_postid()`. This function searches the postmeta table by both meta_key and meta_value. Meta_value() cannot be indexed because it's a longtext so you end up with an inefficient query that can run on a page multiple times. It was adding anywhere between 0.8s and 1.5s to every page that displayed an author on my site.

## Possible Solution

1. Introducing caching
2. Add a filter get_custom_avatar filter so that users's can introduce their own caching or do things differently
3. Roll back the code to 4.6.x?

## Steps to Reproduce (for bugs)

1. Have a site with lots of posts and lots of metadata per post
2. Render an author with a custom avatar on a page
3. Look the Query Monitor tool bar light up

## Context

I just want an author with a custom avatar on a page.

## Your Environment

* Version used: 4.7.2
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Ubuntu 22.04.1-Ubuntu (Kernel 6.8.0-47-generic)

**Comment by ojopaul** [comment]
Hi @c0ntax, Thanks for your report.

Right now, we're using attachment_url_to_postid to get avatar post id so we can retrieve avatar alt text from their post as requested by users but I agree with you such function should be filtereable in case of large site users like yours.

So, we introduced a filter in the coming release with information [here](https://github.com/publishpress/PublishPress-Authors/pull/1961).

You can use the filter and simply return "Avatar" or any non null value to prevent the function from querying for avatar alt.

Thanks
