### ISSUE TITLE
Missing Schema on Page

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1926]
Step to replicate:
1. Install PP Authors + Yoast
2. Create new pages
3. Assign 3 authors with different Author Categories
4. Check on validator schema
5. It will only show 1 author

Only happens on Page. Post works fine

**Comment by ojopaul** [comment]
**I'm adding this comment incase we have another report that'll warrant removing this solution.**

> Currently, we're only updating Author parameter if it's in existing yoast meta data but seems original yoast meta data doesn't contain Author information for page.
> 
> I'll remove that condition to make sure authors data are always added even if the original meta data doesn't contain it and see if we get any report of abnormalities
