### ISSUE TITLE
Brazil Translation

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#1927]
[Archive.zip](https://github.com/user-attachments/files/17648362/Archive.zip)

**Comment by ojopaul** [comment]
@rizaardiyanto1412 This seams to be only for Authors pro?

**Comment by rizaardiyanto1412** [comment]
@ojopaul Yes, sorry forgot to inform.
This is from our translator, and they just got a chance to do the Pro one. Not yet for the free

**Comment by ojopaul** [comment]
All right, Thanks @rizaardiyanto1412

**Comment by ojopaul** [comment]
The package is same as what was updated and released in 4.7.2 https://github.com/publishpress/PublishPress-Authors/issues/1910
