### ISSUE TITLE
Doesn't work as a mu-plugin

### ISSUE THREAD

**Issue by johnbillion** [publishpress/PublishPress-Authors#20]
When installing this plugin as a mu-plugin, the enqueued CSS/JS assets return 404s.

It looks to be caused by the `PP_AUTHORS_ASSETS_URL` constant which incorrectly uses `plugin_url()` instead of `plugin_dir_url()`.

**Comment by stevejburge** [comment]
Thanks for the helpful feedback, @johnbillion. We'll get this fixed in the next release

**Comment by stevejburge** [comment]
@johnbillion Thanks again. This should be fixed in 3.2
