### ISSUE TITLE
Unlike the Free version, the Pro version is not responsive to html tag under the biographic Info.

### ISSUE THREAD

**Issue by seth8373** [publishpress/PublishPress-Authors#201]
**Is your feature request related to a problem? Please describe.**
The Free version allows for html tag to be applied to the text in the Biographic Information. The effect of the tag is responsive at the front. On the other hand, the Pro version (version 3.5.0) is not responsive to html tag.

**Describe the solution you'd like**
Pro Version:  The text in the Biographic Info is supposed to be responsive to embedded html tag 

**Describe alternatives you've considered**

**Additional context**
Testing was completed in the following order:
1. Install and activate the latest Free version on WordPress and then complete test
2. Delete the Free version
3. Install and activate the Pro version (3.5.0) and then complete test
**Free version- Bold html tag**
![Bold_Text_Free](https://user-images.githubusercontent.com/65332667/90946381-61727e80-e3e9-11ea-88c6-66a3d7215138.PNG)
![Bold_Text_Free_Front_End](https://user-images.githubusercontent.com/65332667/90946385-72bb8b00-e3e9-11ea-9ec5-1c8a207502fd.PNG)
**Pro Version-Bold html tag**
![Bold_Text_Pro_Front_End](https://user-images.githubusercontent.com/65332667/90946396-98e12b00-e3e9-11ea-957a-be294f54a683.PNG)

**Comment by stevejburge** [comment]
@andergmartins Maybe the best approach is a note saying plain text only? Or should we allow HTML?

**Comment by stevejburge** [comment]
One more request for fixing this

**Comment by andergmartins** [comment]
Duplicated request. This was fixed on issue #267.

But the fix won't update the current custom layouts a Pro user has. So users will need to manually update their layouts adding the filter `raw` to the description field, like in the following code snippet:

![image](https://user-images.githubusercontent.com/407131/100241999-10f04d00-2f13-11eb-8afa-a5f5f80724b5.png)
