### ISSUE TITLE
In authors pro, two author information automatically appear on the bottom of each post 

### ISSUE THREAD

**Issue by qamaricel** [publishpress/PublishPress-Authors#202]
## Expected Behavior

In Authors Pro, from Authors> Settings> Display , once the option "This will display the authors box at the end of the content." is selected, the author box is expected to be displayed once. 
![2 author boxes appear on the bottom of the post](https://user-images.githubusercontent.com/69988967/90988442-05763a00-e550-11ea-9a30-b85c2122df24.jpg)
![Two author boxes automatically appear after every post](https://user-images.githubusercontent.com/69988967/90988444-060ed080-e550-11ea-8fca-8fd973f1fbe3.jpg)

## Current Behavior

In Authors Pro, from Authors> Settings> Display , once the option "This will display the authors box at the end of the content." is selected, the same author box displays two times. The post has only 1 author.

## Steps to Reproduce (for bugs)

1.  From wp-admin account, select Authors>Settings> Display
2.  Select the option or put a check mark on "This will display the authors box at the end of the content."
3.  Select 'Save Changes'
4.  Refresh Wordpress site
5. Two author boxes automatically appear on every post in the site

## Your Environment

* Version used: 5.5
* Browser Name and version: Google Chrome Version 84.0.4147.135 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Desktop
* Link to your project: http://www.momcpreneur.dev.cc

**Comment by stevejburge** [comment]
Hi @qamarice. As a Pro user, can you open a support ticket on our site, please.

If we confirm this is a bug, we'll re-open this issue.

**Comment by qamaricel** [comment]
Thanks Steve. I will open a support ticket then.
