### ISSUE TITLE
Stop using cap- for imports from Co-Authors Plus

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#204]
Related to https://github.com/publishpress/PublishPress-Authors/issues/203

Let's stop using cap- for imports from Co-Authors Plus:

![Screen Shot 2020-08-24 at 9 39 38 AM](https://user-images.githubusercontent.com/3868028/91051354-02318b80-e5ee-11ea-8f78-47457777b1e1.png)
![Snap9](https://user-images.githubusercontent.com/3868028/91051360-0362b880-e5ee-11ea-9aa3-aef1f7ac4d39.png)

**Comment by andergmartins** [comment]
@stevejburge This can be fixed using the option to import Co-Authors data:

<img width="1280" alt="Screen Shot 2020-08-25 at 17 19 48" src="https://user-images.githubusercontent.com/407131/91223567-3644a380-e6f7-11ea-92b1-72667a5f190f.png">

That button is available if Co-Authors Plus is activated.

Both plugins use the same taxonomy: "authors" so we are not migrating anything automatically, just showing co-authors data together "by coincidence". But running that migration task fixes it.

**Comment by stevejburge** [comment]
@andergmartins Interesting - thanks.

Perhaps the only solution is to show a message to CAP users, asking them to migrate?

**Comment by andergmartins** [comment]
@stevejburge I think so. I added the notice yesterday. Closing this issue.
