### ISSUE TITLE
Changing Author's URL link results in link not working properly

### ISSUE THREAD

**Issue by seth8373** [publishpress/PublishPress-Authors#205]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1.1. Install WordPress 5.5
2. Install and activate publishpress-authors-pro-3.5.0 (install from zip file on local drive)
3.  Go to Users->Add New-> complete all edit boxes-> click Add User button
4. Install and activate the "Edit Author Slug" plugin
5. Go to “Users” in your WordPress admin menu.
6. Edit the user URL you want to change
7. Go to “Authors” in Wordpress admin menu – (The Author URL in the right column in the table is the same as the changed User Edit Author Slug)
8.  Settings > Permalinks and click “Save Changes”
9. Click on "Author URL"  in "Authors" table

**Note:** 
Clicking on the changed Author URL results in an error

The "Author URL" in the right column in the "Authors"  table is the same as the changed new name specified in the  "Edit Author Slug", however, clicking on "Edit Author Profile" tab in the "Authors"  table shows the "Author URL" did not change under "Edit Author". 
Choosing the user again under “Mapped User” and Clicking “Update” does not update the "Author URL" under "Edit Author".

## Your Environment
 Tested locally on Bitnami WordPress 5.5-0 

* Version used:
* Browser Name and version: Google Chrome, Version 84.0.4147.135 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):Windows 10, Desktop
* Link to your project:

![Capture_C](https://user-images.githubusercontent.com/65332667/91101965-78051980-e625-11ea-9a0d-4b5c5baca5d9.PNG)

![Capture_E](https://user-images.githubusercontent.com/65332667/91102171-e34eeb80-e625-11ea-838e-1dbd8e3e1606.PNG)

![Capture_D](https://user-images.githubusercontent.com/65332667/91101902-4d1ac580-e625-11ea-97e1-e0cddc7179e9.PNG)

![Capture_E](https://user-images.githubusercontent.com/65332667/91102651-d4b50400-e626-11ea-8c80-bb3924f2a220.PNG)

![Capture_G](https://user-images.githubusercontent.com/65332667/91102039-a256d700-e625-11ea-92f8-d91866ab5908.PNG)

**Comment by andergmartins** [comment]
Related to #128

**Comment by andergmartins** [comment]
Duplicates #53

**Comment by andergmartins** [comment]
Thanks for the contribution @seth8373. I'm working on fixing this issue on ticket #53. You can follow the progress there.
