### ISSUE TITLE
Editors should be able to assign an author

### ISSUE THREAD

**Issue by johnbillion** [publishpress/PublishPress-Authors#21]
Related: #10.

By default, a user with the role of Editor can choose which user is assigned as the author of a post that they edit or publish (from the `Author` dropdown in the `Status and Visibility` meta box).

With PublishPress Authors active, editors can no longer choose the author of a post which means that only administrators can control the assigned author of a post.

**Comment by andergmartins** [comment]
Hi @johnbillion thank you for reporting it. You are right, we do ned to improve this.

Right now, after adding the capabilities ppma_edit_orphan_post, edit_others_posts we allow to see the author box. But the author can only be edited by users with ppma_manage_authors.

We are going to work to simplify and fix this.

**Comment by stevejburge** [comment]
@johnbillion Thanks for the nudge. This is solved in 3.2.0 with a new "ppma manage authors" capability

**Comment by funbinod** [comment]
> @johnbillion Thanks for the nudge. This is solved in 3.2.0 with a new "ppma manage authors" capability

I'm using version 3.3.0. But couldnot find out how can i go through this "ppma manage authors". Can you please elaborate? I need to allow all user types to manage authors for each post.

**Comment by stevejburge** [comment]
@funbinod Does this issue sound like what you need?
https://github.com/publishpress/PublishPress-Authors/issues/10

**Comment by funbinod** [comment]
> @funbinod Does this issue sound like what you need?
> #10

Yes! the issue is related to #10. I read the whole issue and came here. Here you have mentioned that 3.2.0 has the solution, so replied to this.
