### ISSUE TITLE
Authors dropdown is missing

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#213]
Following up on a couple of reports from users, I confirmed this bug. Users in the "Author" role can't add authors. 

Oddly, users in the "Contributor" and "Editor" role can see the box. It's just the "Author" role that's a problem.

<img width="325" alt="Screen Shot 2020-09-02 at 3 32 08 PM" src="https://user-images.githubusercontent.com/3868028/92028365-e6d32880-ed31-11ea-8970-fead406ed2ff.png">

**Comment by andergmartins** [comment]
Related to #10
