### ISSUE TITLE
Allow authors to update their own information

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#24]
We should provide some way for users to update their own author.

Maybe the author info should appear on people's Profile pages?

Here's one user asking about the bio field:

>     I have an issue with the multiple authors feature concerning the authors bio.
> 
>     When I update the "biographical info" of a user, the biographical info of the author mapped to that user does not change and vice versa.
> 
>     This has turned out to be a problem because we give users the possibility to log in and change their own bio but this change doesnt become visible on the website...
> 
>     It would be really cool to have a checkbox to sync between those data.

**Comment by stevejburge** [comment]
Perhaps the easiest solution is to allow users access to the "Authors" page so they can update their own user profile.

**Comment by andergmartins** [comment]
One new request for this

**Comment by andergmartins** [comment]
It should be possible for authors to access "Authors" and edit their own profile.

Create a permission for access to the "Authors" screen
The default is that you only see your own Mapped User profile
Create a second permission for "View all Authors"
