### ISSUE TITLE
"Default Author For New Posts" Option Not Displaying 

### ISSUE THREAD

**Issue by seth8373** [publishpress/PublishPress-Authors#242]
## Expected Behavior
Go to “Authors” in your WordPress admin menu and clicking “Settings” should allow you to choose the Author from the “Default author for new posts” option

## Current Behavior
Going to “Authors” in your WordPress admin menu and clicking “Settings” does not display Author from the “Default author for new posts” option

## Steps to Reproduce (for bugs)

1. Go to “Authors” in your WordPress admin menu.
2. Click “Settings”.
3. Look for “Default author for new posts” option
Note: Clicking on "Settings" does not invoke the “Default author for new posts” option 

## Your Environment
Bitnami Wordpress-5.5.1-0

* Version used:Pro Version 3.5.0
* Browser Name and version: Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version (desktop or mobile):Windows 10
* Link to your project:

**“Default author for new posts” option Per the Documentation**
![image](https://user-images.githubusercontent.com/65332667/93122129-33e4c200-f683-11ea-8bef-5353c7774d29.png)

**Comment by andergmartins** [comment]
Thanks for reporting that @seth8373
