### ISSUE TITLE
Add profile field sorting options to the Authors List

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#257]
> Can we display a top 10 of authors with the most articles ?

This could be an extra option inside the Authors List widget. Sort by:
- most articles
- newest author etc

**Comment by stevejburge** [comment]
Maybe some filters too. For example:

> Supose I whant to list authors by category on a front page. It wold be simple if there was a short-code to get all authors with a specefiable custom fild. Like [list-all-authors custom-fild="category-slug" custom-fild-valu="fantasy"]

**Comment by andergmartins** [comment]
We got 2 requests for this feature this week. Here is the last one:

>Hi, I'm using the All Authors plugin in a sidebar to create a list of all authors. Is it possible to have them sorted alpha by Last Name, instead of First? I see no option for that, but perhaps that is a paid feature?

**Comment by stevejburge** [comment]
> On the team page I have used the Authors list ‘boxed’ to display all these authors. They appear in alphabetical order (first name). But I would like to choose the order of authors myself. Is this possible?

https://wordpress.org/support/topic/order-of-authors-using-publishpress/

**Comment by andergmartins** [comment]
More options: Sort by first name, last name, alphabetically, reverse alphabetically.

**Comment by andergmartins** [comment]
Here is a code snippet I sent to a user that asked to sort by the authors' last name:

```php
add_filter('pp_multiple_authors_authors_list_box_args', function($args) {
    if ($args['layout'] !== 'sorted_list') {
        return $args;
    }

    $sortedAuthors = [];

    foreach ($args['authors'] as $author) {
        $sortedAuthors[$author->last_name] = $author;
    }

    ksort($sortedAuthors);

    $args['authors'] = $sortedAuthors;

    return $args;
});
```

**Comment by ojopaul** [comment]
@stevejburge i think we have this partly sorted out already. Wondering if i can get overview of what's expected to be added as sort option in addition to what we currently have?
1. Sort by last name
2. Sort by first name
3. Sort by registration date etc?

**Comment by stevejburge** [comment]
My guess is that last name is a big one. Anything else can wait for customer feedback

**Comment by ojopaul** [comment]
@stevejburge sorry, i do not understand, do you mean we should add:
1. Sort by last name
2. Sort by first name
3. Sort by registration date etc?


or just
1. Sort by last name

**Comment by stevejburge** [comment]
Let's do 1 and 2, please

**Comment by ojopaul** [comment]
### Documentation note

It's now possible to order by profile fields.
Example: `first_name` `last_name` `custom_field_slug` etc

@stevejburge
