### ISSUE TITLE
Author vs Authors text

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#282]
The default behavior is to have the same title 1 author:
<img width="941" alt="author-1" src="https://user-images.githubusercontent.com/3868028/100244887-71788d80-2f05-11eb-99ee-49a351391566.png">

And multiple authors:
<img width="948" alt="authors-2" src="https://user-images.githubusercontent.com/3868028/100244936-7e957c80-2f05-11eb-90dd-58a5a21d76b4.png">

Should we replace this setting with a Single and Plural field? Maybe use it in the widget too?
<img width="652" alt="Screen Shot 2020-11-25 at 10 03 52 AM" src="https://user-images.githubusercontent.com/3868028/100245006-9240e300-2f05-11eb-8ae2-f1477e696d63.png">

**Comment by andergmartins** [comment]
Closing this as duplicated on #75
