### ISSUE TITLE
Make it easy to see author URLs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#30]
In the admin area, there's no way to see the frontend URL for author's pages.

Maybe we make the "Author URL" column into clickable links?

<img width="806" alt="Screen Shot 2020-03-02 at 12 29 38 PM" src="https://user-images.githubusercontent.com/3868028/75701311-892a2a80-5c81-11ea-8725-7fe83c0ca44d.png">

**Comment by andergmartins** [comment]
That is already implemented. Closing the ticket.
