### ISSUE TITLE
Show the author bio on the archive pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#31]
One user asked us if they can show the author's image, fields, profile etc on their archive pages

Could this be done by selecting a layout option (Boxed, Inline etc)

Or maybe we improve the widget so that it detects archive pages and shows the appropriate author?

At the moment, the author pages are definitely lacking ...

![Screen Shot 2020-03-02 at 12 31 05 PM](https://user-images.githubusercontent.com/3868028/75701470-da3a1e80-5c81-11ea-98e3-57e0f2f0cd64.png)

**Comment by andergmartins** [comment]
@stevejburge this can be done adding the shortcode to the archive page in the theme using child themes:

​[author_box layout="boxed" archive="true"]

Note the "archive" param in the shortcode. I just updated the documentation [here](https://publishpress.com/knowledge-base/shortcodes/) to mention that param. 

Adding the archive param helps the plugin to detect the correct author and display the selected layout.
