### ISSUE TITLE
Add author URLs to REST API support

### ISSUE THREAD

**Issue by Absotively** [publishpress/PublishPress-Authors#318]
I looked into implementing [PublishPress Blocks issue #143](https://github.com/publishpress/PublishPress-Blocks/issues/143), support for PublishPress Authors in the Recent Posts block. In order to render the links in the preview in the block editor correctly, PublishPress Blocks would need to get the author display names and URLs from the REST API. #311 adds the display names, so the URLs are all that's missing now.

Note that support in the actual site doesn't need this, so another option would be for PP Blocks to just have a slightly less accurate preview for Recent Posts when PP Authors is installed.

**Comment by stevejburge** [comment]
Thanks so much @Absotively. This is 100% the direction we're taking with PublishPress Blocks (more features for publishers, and more integration with our plugins). We'll get this done.

**Comment by stevejburge** [comment]
Closing as #311 will be in the next release of Authors
