### ISSUE TITLE
Improve the design of the boxed layout

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#320]
Our default design is quite plain.

One comparison:

https://demo.mekshq.com/gridlove/?p=368
<img width="732" alt="Screen Shot 2021-01-12 at 10 06 42 AM" src="https://user-images.githubusercontent.com/3868028/104332225-f6236900-54bd-11eb-87ff-892cbc14ffbc.png">

**Comment by htmgarcia** [comment]
@stevejburge current proposal in different themes. Note there is a small spacing issue on the "View all posts" button on Twenty Twenty-One theme.
<img width="915" alt="Screen Shot 2021-01-28 at 13 38 57" src="https://user-images.githubusercontent.com/4999794/106189960-93dd9000-616e-11eb-9b65-d3cc9c5563a4.png">
<img width="637" alt="Screen Shot 2021-01-28 at 13 39 47" src="https://user-images.githubusercontent.com/4999794/106189953-917b3600-616e-11eb-87f4-251eed8c1f59.png">
<img width="605" alt="Screen Shot 2021-01-28 at 13 39 34" src="https://user-images.githubusercontent.com/4999794/106189956-92ac6300-616e-11eb-9fca-ca5e5a4e202a.png">
<img width="714" alt="Screen Shot 2021-01-28 at 13 39 16" src="https://user-images.githubusercontent.com/4999794/106189958-9344f980-616e-11eb-8d18-92efbe882c75.png">

**Comment by stevejburge** [comment]
Awesome, thanks @htmgarcia

**Comment by htmgarcia** [comment]
@stevejburge with this change to boxed layout (is not the default one), I think worth to set boxed layout as default.
cc @andergmartins
