### ISSUE TITLE
Errors showing in the PublishPress Log

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#355]
PublishPress Authors has been flooding the PHP error log of publishpress.com with this warning since 9/4/2020:

```
[PublishPress Authors] Twig file not found for the layout: custom. Falling back to "simple_list"
occasional glitch since 9/4/2020:
```
Another occasional glitch since 9/4/2020:
`[PublishPress Authors] Error found while getting author's name attribute (term_id = 2866): Invalid taxonomy.`

getting these sporadically, since 5/5/2020 and as recently as 1/21/2021:

`[PublishPress Authors] Warning - The link for the author_id="0" was changed to the post page because the author is not specified in the given url`

**Comment by andergmartins** [comment]
```
[PublishPress Authors] Twig file not found for the layout: custom. Falling back to "simple_list"
occasional glitch since 9/4/2020:
```
This one is fixed on the issue #336 waiting to be released.

**Comment by andergmartins** [comment]
```
[PublishPress Authors] Error found while getting author's name attribute (term_id = 2866): Invalid taxonomy.
```
Related to #326

**Comment by andergmartins** [comment]
```
[PublishPress Authors] Warning - The link for the author_id="0" was changed to the post page because the author is not specified in the given URL
```
Related to #308

**Comment by andergmartins** [comment]
Closing this because all the 3 error messages are fixed on the respective issues.
