### ISSUE TITLE
Inline with Avatar does not properly appear 

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#36]
Step 1: Go to   Authors > Settings and click the “Display” tab

![InlineWithAvatar](https://user-images.githubusercontent.com/62157750/76910668-e28e7e00-686b-11ea-9b29-80b9ecd53958.PNG)

Step 2: Make sure that “This will display the authors box at the end of the content” is checked
Step 3: Select "Inline with Avatars" layout
Step 4: Click "Save Changes" button
Step 5: Refresh post
 
Note: The "Inline with Avatars" is not shown as described. It looks more like a list with Avatars.

**Comment by stevejburge** [comment]
Good point, thanks @JulieBanu

**Comment by htmgarcia** [comment]
@JulieBanu this has been fixed. Please update PublishPress Authors.

<img width="435" alt="Screen Shot 2020-04-15 at 18 24 00" src="https://user-images.githubusercontent.com/4999794/79398654-cbb07980-7f46-11ea-867e-7f214d552375.png">
