### ISSUE TITLE
Color picker for frontend layouts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#377]
We've added some colored items to the frontend layouts.

They are purple by default. Can we add a color picker to the settings?

![Screen Shot 2021-02-25 at 11 51 04 AM](https://user-images.githubusercontent.com/3868028/109187295-c1166180-775f-11eb-97ff-153e160f9d05.png)

**Comment by htmgarcia** [comment]
@stevejburge do you mean through Settings > Display tab, correct?
<img width="653" alt="Screen Shot 2021-02-25 at 15 25 52" src="https://user-images.githubusercontent.com/4999794/109219891-d5695700-777d-11eb-9ca4-cd2debc046a4.png">

**Comment by stevejburge** [comment]
Yes, please

**Comment by htmgarcia** [comment]
@stevejburge maybe the label needs a review. This new setting only affects links with button style for boxed and centered layouts.

@andergmartins not sure if I'm missing something; I would expect a different look for the color picker field.

<img width="662" alt="Screen Shot 2021-02-26 at 11 21 43" src="https://user-images.githubusercontent.com/4999794/109333393-05b80080-7825-11eb-8540-20e66d02f19e.png">
