### ISSUE TITLE
"Centered" Layout does not appear as described

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#38]
Step 1: Go to   Authors > Settings and click the “Display” tab
--
Step 2: Make sure that “This will display   the authors box at the end of the content” is checked
Step 3: Select "Centered"   layout
Step 4: Click "Save Changes"   button
Step 5: Refresh post
 
Note: The    "Centered" layout does not show as described. The alignment   shown is left, not center.

![CenteredLayout](https://user-images.githubusercontent.com/62157750/76990822-d0f9b480-6905-11ea-99a9-cd192ea26300.PNG)

**Comment by htmgarcia** [comment]
Many improvements were implemented. I just added small tweaks:
<img width="752" alt="Screen Shot 2020-04-14 at 19 11 05" src="https://user-images.githubusercontent.com/4999794/79285647-c50cfe00-7e83-11ea-8baf-f385cc4134a0.png">
