### ISSUE TITLE
Remove dash after the name in "Simple list" layout.

### ISSUE THREAD

**Issue by VadymMalinovskyi** [publishpress/PublishPress-Authors#40]
My recommendation is to remove dash after the name of author or make avatar close to the dash for better visual appearance.

<img width="970" alt="Снимок экрана 2020-03-18 в 15 49 56" src="https://user-images.githubusercontent.com/55210526/77014793-4f6b4c00-6930-11ea-8b77-52fc04151c52.png">

**Comment by htmgarcia** [comment]
@stevejburge moving the avatar to the left:
<img width="729" alt="Screen Shot 2020-04-14 at 18 20 31" src="https://user-images.githubusercontent.com/4999794/79283260-e7e7e400-7e7c-11ea-9821-4fb5f21eaedf.png">
