### ISSUE TITLE
The line under the name of author is too long in "Inline with avatar" layout.

### ISSUE THREAD

**Issue by VadymMalinovskyi** [publishpress/PublishPress-Authors#41]
Note: Line goes under the avatar.
<img width="690" alt="Снимок экрана 2020-03-18 в 15 57 17" src="https://user-images.githubusercontent.com/55210526/77015141-2a2b0d80-6931-11ea-958b-0fc30aa73509.png">

**Comment by htmgarcia** [comment]
@VadymMalinovskyi which theme are you using?

**Comment by VadymMalinovskyi** [comment]
@htmgarcia Twenty Sixteen

**Comment by htmgarcia** [comment]
@VadymMalinovskyi this was already fixed. Last update was from 2 days ago.
<img width="435" alt="Screen Shot 2020-04-15 at 18 24 00" src="https://user-images.githubusercontent.com/4999794/79398501-73797780-7f46-11ea-893c-b61e01d462c8.png">
