### ISSUE TITLE
Authors not created automatically if registered from the frontend

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#420]
I can confirm this bug:

> Is there any way to "Automatically create author profiles" when someone registers? At the moment it only works if an admin creates a new user from within the WordPress Dashboard.

**Comment by FrityTrump** [comment]
I confirm this is a bug also:

"Automatically create author profiles" doesn't work when someone registers from the frontend or wp-login.php. It only works if an admin creates a new user from within the WordPress Dashboard.

**Comment by FruityTrump** [comment]
I confirm this is a bug also:

"Automatically create author profiles" doesn't work when someone registers from the frontend or wp-login.php. It only works if an admin creates a new user from within the WordPress Dashboard.

**Comment by FruityTrump** [comment]
> 
> 
> I can confirm this bug:
> 
> > Is there any way to "Automatically create author profiles" when someone registers? At the moment it only works if an admin creates a new user from within the WordPress Dashboard.

Anyone know why this is happening?

**Comment by stevejburge** [comment]
@FruityTrump This feature was built for a PublishPress customer who wanted to add users via the admin

**Comment by FruityTrump** [comment]
> 
> 
> @FruityTrump This feature was built for a PublishPress customer who wanted to add users via the admin

If this was the way it was intended to work... How is "Authors not created automatically if registered from the frontend" a bug?

**Comment by stevejburge** [comment]
@FruityTrump I changed the label. But at the end of the day, it's still on our roadmap as an improvement.
