### ISSUE TITLE
No Longer Able to Designate Authors in WP Editor

### ISSUE THREAD

**Issue by BobLaycock** [publishpress/PublishPress-Authors#422]
The field for designating authors is missing from my WordPress editor. I remain the author by default but can no longer designate a Guest Author. All previous author designations appear correctly in my published posts. The issue is just the editor. I've deactivated & reactivated the plugin, also deleted and reinstalled. I'm using the latest version as of this writing (4/9/21) on the Tortuga theme in WordPress. I'm not sure when this started, but my last post with a Guest Author was January 11th so the problem began sometime since then. The problem exists in the Mac desktop app for WordPress, as well as when I access the editor on Safari and Chrome.

**Comment by stevejburge** [comment]
Hi @BobLaycock. Thanks for reporting this. However, there's little information for us to work with here.

Please fill in the full information requested when you click "New issue"

**Comment by BobLaycock** [comment]
I hope this helps. Essentially nothing I know of has changed since January 11th when I last needed PublishPress Author and it worked as expected.

## Expected Behavior


When editing a new or existing post, the Post Section of the Settings Panel would include a section for Author near or at the bottom. I was always the default author but could add a new author or select from a list of previously-created authors.

## Current Behavior


The Author Section described above missing entirely on all platforms I use to access the WP Editor (Mac desktop app, Safari, Chrome and Firefox).

## Possible Solution


As far as I know there's nothing I've done at my end to create the problem. I'm running all the current versions of WordPress, my theme, and the plugin. WP updates the Mac desktop app fairly frequently, but the problem isn't limited to the Mac app as noted. It's on the web portals as well. I've added one new plugin recently (Simple Lightbox) but it does not appear to be interfering with PublishPress Authors. I tested PublishPress  with Simple Lightbox deactivated.

## Steps to Reproduce (for bugs)


1. There's not much to say. I edit as usual but the Authors section is missing from the WP Editor.

## Context



I use the plugin when posting something written by someone other than myself, a Guest Author. I use the plugin to designate this Guest Author and to enable visitors to find all other posts written by that person. With the Author Section missing I am no longer able to designate any authors other than myself (default by site ownership).

## Your Environment


* WP Mac Version used: 6.13.0
* WP Theme: Tortuga -- https://wordpress.org/themes/tortuga/
* PublishPress Author Version: 3.13.0
* Browser Name and version: Safari 14.0.3 / Chrome 89.0.4389.114 / Firefox 87.0
* Operating System and version (desktop or mobile): Mac Big Sur 11.2.3
* Link to your project: https://justsayin2.com

**Comment by stevejburge** [comment]
Hi @BobLaycock, sorry we've not seen anything like this from other users. 

Maybe there's an error showing in your browser console?
https://publishpress.com/knowledge-base/debug-errors-publishpress-screens/

Unless you can show us how to re-create this, it's more of a question for our support team: https://publishpress.com/publishpress-support/

**Comment by BobLaycock** [comment]
Thanks. I guess I'll follow up with support. Since the situation is happening across all browsers and the WP desktop app, I somehow doubt debugging a browser will help. Thanks again!

**Comment by stevejburge** [comment]
Thanks @BobLaycock
