### ISSUE TITLE
Warning: Creating default object in PublishPress Error logs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#432]
> Warning: Creating default object from empty value in /home/137842.cloudwaysapps.com/tukyvtwwrk/public_html/wp-content/plugins/publishpress-authors-pro/vendor/publishpress/publishpress-authors/src/core/Classes/Objects/Author.php on line 174

<img width="601" alt="Screen Shot 2021-04-23 at 9 49 32 AM" src="https://user-images.githubusercontent.com/3868028/115880935-3d07ef80-a419-11eb-8fbe-87f588e066fb.png">

**Comment by andergmartins** [comment]
Another report:

>2021/05/04 14:19:11 [error] 22306#0: *25195321 FastCGI sent in stderr: "PHP message: [PublishPress Authors] A term with the name provided already exists in this taxonomy. MultipleAuthors\Classes\Objects\Author::createPHP message: PHP Warning: Creating default object from empty value in /usr/local/nginx/html/wp-content/plugins/publishpress-authors-pro/vendor/publishpress/publishpress-authors/src/core/Classes/Objects/Author.php on line 174PHP message: PHP Fatal error: Uncaught Error: Call to undefined method stdClass::is_guest() in /usr/local/nginx/html/wp-content/plugins/publishpress-authors-pro/vendor/publishpress/publishpress-authors/src/modules/rest-api/rest-api.php:122
Stack trace:
$0 /usr/local/nginx/html/wp-includes/rest-api/endpoints/class-wp-rest-controller.php(433): MA_REST_API->getPostAuthorsCallBack(Array, 'authors', Object(WP_REST_Request), 'post')
$1 /usr/local/nginx/html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1880): WP_REST_Controller->add_additional_fields_to_object(Array, Object(WP_REST_Request))
$2 /usr/local/nginx/html/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(367): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
$3 /usr/local/nginx/html/wp-includes/rest-api/class-wp-rest-server.php(1139): WP_REST_Posts_Controller->get_items(Object(WP_REST_Request))
$4 /usr/local/nginx/html/wp-includes/rest-api/class-wp-rest-server.p" while reading response header from upstream, client: 120.0.30.50, server: altnuxt.com, request: "GET /index.php/wp-json/wp/v2/posts?per_page=1&_embed=wp:term,author,wp:featuredmedia&slug=cbt-school-welcomes-new-instructor HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/www.sock::", host: "charlestoncitypaper.altnuxt.com"

>Deleting the existing author profiles that were linked to users and then re-adding them seems to have resolved the issue.

**Comment by stevejburge** [comment]
Solved

**Comment by andergmartins** [comment]
Probably fixed on v3.14.3
