### ISSUE TITLE
Schema from Yoast SEO stopped working

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#472]
The Yost SEO integration module needs to be updated.

The Schema classes need to be updated to use the most recent versions of the Yoast SEO classes.
They started using namespaces for the classes, so we need to update the function `handleSchemaGraphPieces` for detecting the new namespaces:

`src/modules/yoast-seo-integration/src/SchemaFacade.php`

From:

```php
$schemaMap = [
            'WPSEO_Schema_Article' => Schema\Article::class,
            'WPSEO_Schema_Author'  => Schema\Author::class,
            'WPSEO_Schema_Person'  => Schema\Person::class,
            'WPSEO_Schema_WebPage' => Schema\Webpage::class,
        ];
```

To something like:

```php
$schemaMap = [
            'Yoast\\WP\\SEO\\Generators\\Schema\\Article' => Schema\Article::class,
            'Yoast\\WP\\SEO\\Generators\\Schema\\Author'  => Schema\Author::class,
            'Yoast\\WP\\SEO\\Generators\\Schema\\Person'  => Schema\Person::class,
            'Yoast\\WP\\SEO\\Generators\\Schema\\Website' => Schema\Webpage::class,
        ];
```

Could it display multiple authors?

**Comment by andergmartins** [comment]
Related to the ticket https://secure.helpscout.net/conversation/1578555784/148249?folderId=2557470 (private link)

**Comment by nydame** [comment]
Thanks for following up on this!

**Comment by stevejburge** [comment]
Can confirm: 
https://taxopress.com/author/steve/
![Screen Shot 2021-08-19 at 11 37 06 AM](https://user-images.githubusercontent.com/3868028/130098681-2a96c87e-ccf5-4dad-9225-cbf7bea06925.png)
