### ISSUE TITLE
Authors byline stopped working after v3.14.2

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#473]
Users reported that the authors byline stopped showing in the frontend after they updated to v3.14.2.

On some sites they now see the admin as the author of posts. Maybe that happens for guest authors?
Some of them didn't have any customization in the theme.

**Comment by andergmartins** [comment]
I think it happens for sites that don’t use any snippet on their theme for making it compatible with our plugin. 
I was able to reproduce the bug on the theme Twenty Twenty-One, for a post with a guest author.

Our integration tests have a problem because no tests are failing. We need to be sure a test fails for this use case.

If I revert the fix of #463 it works again. Maybe we need a conditional to only apply that fix for the Gutenberg editor.

**Comment by andergmartins** [comment]
Reopening for a new report:

>it is displaying correctly, now, but still doesn't work in the editor. When I add the author box (via Elementor Pro), the only author name/bio that gets posted is mine.

**Comment by annamarypatty** [comment]
Is there a fix for this yet? I have a site with over 200 posts that are currently displaying the wrong authors.

**Comment by andergmartins** [comment]
Hi @annamarypatty yes, we have a beta package addressing this bug, planned to be released next Monday.
Here is a link if you wanna test the free version. If you need the Pro version, feel free to contact us by emailing [help@publishpress.com](mailto:help@publishpress.com).

https://www.dropbox.com/s/hzci4tdafbpj85u/publishpress-authors-3.14.3-beta.3.zip?dl=0

**Comment by annamarypatty** [comment]
I am still getting the wrong author in the author box each time I try to update. I am currently rolling back to version 3.14.1. It appears to pull in the correct author information everywhere else, including the author bio and image in the author box, it is just the author name in the author box that is pulling the WP user instead of the actual author name. Please help!
