### ISSUE TITLE
Errors with translations going to WordPress.org

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#493]
https://make.wordpress.org/plugins/2015/12/06/plugin-translations-for-all-plugins/

WordPress Slack is reporting errors

![Screen Shot 2021-08-24 at 4 55 02 PM](https://user-images.githubusercontent.com/3868028/130688661-21d3ee19-6674-48ad-bf64-7f10878e5e9e.png)

**Comment by andergmartins** [comment]
@stevejburge I think everything is good. It only says it skipped the not-found translations. But I see all the ones we have there.

Here is the complete log: 

>Skip af, no translations.
    Skip sq, no translations.
    Skip arq, no translations.
    Skip am, no translations.
    Skip ar, no translations.
    Skip arg, no translations.
    Skip hy, no translations.
    Skip frp, no translations.
    Skip as, no translations.
    Skip ast, no translations.
    Skip az, no translations.
    Skip az_TR, no translations.
    Skip bcc, no translations.
    Skip ba, no translations.
    Skip eu, no translations.
    Skip bel, no translations.
    Skip bn_BD, no translations.
    Skip bn_IN, no translations.
    Skip bho, no translations.
    Skip brx, no translations.
    Skip gax, no translations.
    Skip bs_BA, no translations.
    Skip bre, no translations.
    Skip bg_BG, no translations.
    Skip ca, no translations.
    Skip bal, no translations.
    Skip ca_valencia, no translations.
    Skip ceb, no translations.
    Skip zh_CN, no translations.
    Skip zh_HK, no translations.
    Skip zh_SG, no translations.
    Skip zh_TW, no translations.
    Skip cor, no translations.
    Skip co, no translations.
    Skip hr, no translations.
    Skip cs_CZ, no translations.
    Skipping threshold check for da_DK, has existing language pack.
    Success: Language pack for da_DK generated.
    Skip dv, no translations.
    Skip nl_NL, translations below threshold (22%).
    Skip nl_BE, no translations.
    Skip nl_NL_formal, no translations.
    Skip dzo, no translations.
    Skip art_xemoji, no translations.
    Skip en_AU, no translations.
    Skip en_CA, no translations.
    Skip en_NZ, no translations.
    Skip en_ZA, no translations.
    Skipping threshold check for en_GB, has existing language pack.
    Success: Language pack for en_GB generated.
    Skip eo, no translations.
    Skip et, no translations.
    Skip ewe, no translations.
    Skip fo, no translations.
    Skip fi, no translations.
    Skip fon, no translations.
    Skip fr_BE, no translations.
    Skip fr_CA, no translations.
    Skip fr_FR, translations below threshold (4%).
    Skip fy, no translations.
    Skip fur, no translations.
    Skip fuc, no translations.
    Skip gl_ES, no translations.
    Skip ka_GE, no translations.
    Skip de_DE, no translations.
    Skip de_AT, no translations.
    Skip de_DE_formal, no translations.
    Skip de_CH, no translations.
    Skip de_CH_informal, no translations.
    Skip el, no translations.
    Skip kal, no translations.
    Skip gu, no translations.
    Skip hat, no translations.
    Skip hau, no translations.
    Skip haw_US, no translations.
    Skip haz, no translations.
    Skip he_IL, no translations.
    Skip hi_IN, no translations.
    Skip hu_HU, no translations.
    Skip is_IS, no translations.
    Skip ido, no translations.
    Skip ibo, no translations.
    Skip id_ID, no translations.
    Skip ga, no translations.
    Skipping threshold check for it_IT, has existing language pack.
    Success: Language pack for it_IT generated.
    Skip ja, no translations.
    Skip jv_ID, no translations.
    Skip kab, no translations.
    Skip kn, no translations.
    Skip kaa, no translations.
    Skip kk, no translations.
    Skip km, no translations.
    Skip kin, no translations.
    Skip ko_KR, no translations.
    Skip kmr, no translations.
    Skip ckb, no translations.
    Skip kir, no translations.
    Skip lo, no translations.
    Skip lv, no translations.
    Skip lij, no translations.
    Skip li, no translations.
    Skip lin, no translations.
    Skip lt_LT, no translations.
    Skip lmo, no translations.
    Skip dsb, no translations.
    Skip lug, no translations.
    Skip lb_LU, no translations.
    Skip mk_MK, no translations.
    Skip mai, no translations.
    Skip mg_MG, no translations.
    Skip ms_MY, no translations.
    Skip ml_IN, no translations.
    Skip mlt, no translations.
    Skip mri, no translations.
    Skip mr, no translations.
    Skip mfe, no translations.
    Skip mn, no translations.
    Skip me_ME, no translations.
    Skip ary, no translations.
    Skip my_MM, no translations.
    Skip nqo, no translations.
    Skip ne_NP, no translations.
    Skip pcm, no translations.
    Skip nb_NO, no translations.
    Skip nn_NO, no translations.
    Skip oci, no translations.
    Skip ory, no translations.
    Skip os, no translations.
    Skip pap_CW, no translations.
    Skip pap_AW, no translations.
    Skip ps, no translations.
    Skip fa_IR, no translations.
    Skip fa_AF, no translations.
    Skip pcd, no translations.
    Skip art_xpirate, no translations.
    Skip pl_PL, no translations.
    Skip pt_AO, no translations.
    Skip pt_BR, no translations.
    Skip pt_PT, no translations.
    Skip pt_PT_ao90, no translations.
    Skip pt_PT_informal, no translations.
    Skip pa_IN, no translations.
    Skip rhg, no translations.
    Skip ro_RO, no translations.
    Skip roh, no translations.
    Skip ru_RU, no translations.
    Skip sah, no translations.
    Skip sa_IN, no translations.
    Skip skr, no translations.
    Skip srd, no translations.
    Skip gd, no translations.
    Skip sr_RS, no translations.
    Skip sna, no translations.
    Skip sq_XK, no translations.
    Skip scn, no translations.
    Skip szl, no translations.
    Skip snd, no translations.
    Skip si_LK, no translations.
    Skip sk_SK, no translations.
    Skip sl_SI, no translations.
    Skip so_SO, no translations.
    Skip azb, no translations.
    Skip es_AR, no translations.
    Skip es_CL, no translations.
    Skip es_CO, no translations.
    Skip es_CR, no translations.
    Skip es_DO, no translations.
    Skip es_EC, no translations.
    Skip es_GT, no translations.
    Skip es_HN, no translations.
    Skip es_MX, no translations.
    Skip es_PE, no translations.
    Skip es_PR, no translations.
    Skip es_ES, no translations.
    Skip es_UY, no translations.
    Skip es_VE, no translations.
    Skip su_ID, no translations.
    Skip sw, no translations.
    Skip ssw, no translations.
    Skip sv_SE, no translations.
    Skip syr, no translations.
    Skip tl, no translations.
    Skip tah, no translations.
    Skip tg, no translations.
    Skip zgh, no translations.
    Skip tzm, no translations.
    Skip ta_IN, no translations.
    Skip ta_LK, no translations.
    Skip tt_RU, no translations.
    Skip te, no translations.
    Skip th, no translations.
    Skip bo, no translations.
    Skip tir, no translations.
    Skip tr_TR, no translations.
    Skip tuk, no translations.
    Skip twd, no translations.
    Skip ug_CN, no translations.
    Skip uk, no translations.
    Skip hsb, no translations.
    Skip ur, no translations.
    Skip uz_UZ, no translations.
    Skip vec, no translations.
    Skip vi, no translations.
    Skip cy, no translations.
    Skip wol, no translations.
    Skip xho, no translations.
    Skip yor, no translations.
    Skip zul, no translations.
Language packs for publishpress-authors processed.

And here, the current status:

![image](https://user-images.githubusercontent.com/407131/134089170-a7596fbd-bd67-4535-90fe-c2f3a31ad31d.png)
