### ISSUE TITLE
Add option to set a default author for every new post

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#50]
Since we removed the no-author feature a user has suggested we add a global option to set a default author.

If no default author is set new posts will have the current user as author, the default behavior. If set, that author will be used as default for every new post.

**Comment by andergmartins** [comment]
Maybe we could have an option to configure this per post type and/or category?

**Comment by stevejburge** [comment]
One more request for this:

> we post under our organisation name so it would be one less thing for my colleagues to worry about if it was automatic!

**Comment by muhammedmagdi** [comment]
@stevejburge  @andergmartins  I have done this at this pull request: https://github.com/publishpress/PublishPress-Authors/pull/211

**Comment by stevejburge** [comment]
Thanks @muhammedmagdi
