### ISSUE TITLE
Convert author to guest author when its user is deleted

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#505]
When a mapped to user author has its user deleted, the term meta `user_id_<ID>`, and `user_id` are not removed or cleared. 
We need to intercept the user deletion action and convert the author into a guest author.

Related to #142, #491 , #332

**Comment by dknauss** [comment]
How would this accommodate user deletion requests under the GDPR -- or anyone who wants to totally delete someone's data record -- but not something they authored or co-authored?

**Comment by andergmartins** [comment]
Hi @dknauss.

For those who want to totally delete someone's data record, or have better control over that, please check issue #332.
On this issue, we are going to keep all the content, just making sure to fix the author register.
