### ISSUE TITLE
Improved REST API support

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#509]
We have a very limited support for the REST API right now. We are only listing the post users on a custom property authors in the API response body

**Comment by stevejburge** [comment]
This is a common request. Here's one of them:

> Is there a way to create posts with multiple PublishPress authors through the REST API (preferably) or WP CLI? We have thousands of posts on our old site that in many cases will need to be attributed to multiple authors on the new site.
> 
> If this is not supported, I would like to put in a feature request for the REST API and/or WP CLI to be extended in this way.

**Comment by ojopaul** [comment]
@stevejburge

### Here's a note on this

We do have a WP CLI integrated into authors https://github.com/publishpress/PublishPress-Authors/blob/development/src/core/WP_Cli.php and they currently have the following methods:
- `list_posts_without_terms` (This will List all of the posts without assigned authors terms)
- `create_terms_for_posts` (This will add author term for posts which only have the post_author. )
- `assign_author_by_meta_key` (Subcommand to assign coauthors to a post based on a given meta key)

- On 

> "Is there a way to create posts with multiple PublishPress authors through the REST API (preferably)"

Adding post via rest api is not handled by authors but wordpress and it's possible to assign taxonomy term to post simply by adding taxonomy command for example:

> {
>     "title": "The story of Dr Foo",
>     "content": "This is the story content",
>     "status":"publish",
>     "excerpt":"Dr Foo story",
>     "terms": {
>         "author": [ "myterm", "anotherterm" ]
>     }
> }

However, i'm not sure if this update terms meta and will work as standard post authors assignment. So, it worth checking instead to ensure everything works fine.

**Comment by ojopaul** [comment]
@stevejburge aside from the above note (checking inserting authors via rest api), is there any thing you want me to have a look at on this?

**Comment by stevejburge** [comment]
@ojopaul No, this looks like a great start and we can fill in support for extra features as users start to play with it

**Comment by ojopaul** [comment]
@stevejburge 
Here's a documentation note on assigning author via rest api:
The user should add `ppma_author` with array of author's term id to request body as shown in the sample below:

> {
> "title": "The story of Dr Foo",
> "content": "This is the story content",
> "ppma_author": [87],
> "status":"publish",
> "excerpt":"Dr Foo story"
> }

**OR** 

> [
> 'title'         => 'The story of Dr Foo',
> 'content'  =>This is the story content',
> 'ppma_author' => [87, 103],
> 'status'     => 'publish',
> 'excerpt'  => 'Dr Foo story'
> ]

In the two sample above, 87 and 103 are author's term ID
