### ISSUE TITLE
It does not work to update the URLs inside "PublishPress Authors"

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#53]
Step 1:   Install and activate the Edit Author Slug plugin
Step 2:   Go to "Users" in WordPress admin menu
Step 3:   Edit the user whose URL we want to change (in this example the new URL is: "iuli-new-url")

![Users](https://user-images.githubusercontent.com/62157750/77573184-8344f500-6e8d-11ea-9900-027472e5c66c.PNG)

Step 4:   Go to "Authors"
Step 5:   Check if the "Author URL" is correct
Step 6:   If it is not correct, choose the user again under "Mapped User"
Step 7:   click "Update"
Step 8:   Check the "Author URL" box again

![EditAuthor](https://user-images.githubusercontent.com/62157750/77573290-ac658580-6e8d-11ea-9e76-c9ba613f1160.PNG)

Note:   The URL is not updated

**Comment by andergmartins** [comment]
Related to #128
