### ISSUE TITLE
Add shortcode to display specific authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#556]
> what shortcode can I use if I want to show one specific author on a page ?
> 
> For example, I would like to display author which ID is 78 :
> 
> [author_box author_id="78"]

**Comment by ojopaul** [comment]
@stevejburge considering the time this issue was added, i'll like to request for refreshment on the requirement.

Also note, is the author_id referring to wordpress user ID or term id as author's ID? If wordpress user ID, that shows it's limited to wordpress authors and excluding guest author?

**Comment by stevejburge** [comment]
Thanks @ojopaul

With [publishpress_authors_data] can we show one specific author?

**Comment by ojopaul** [comment]
Okay, you missed the last statement below:

Also note, is the `author_id` referring to `wordpress user ID` or `term id`? If `wordpress user ID`, that shows it's limited to wordpress authors and excluding guest author? @stevejburge

**Comment by stevejburge** [comment]
I think the idea would be to use "term id" so we can also show Guest Authors

**Comment by ojopaul** [comment]
### Documentation note:

We added `term_id` to `[publishpress_authors_data]` to get specific authors data by providing the term id. 

Usage: `[publishpress_authors_data term_id="102"]` where 102 is the author term id

@stevejburge
