### ISSUE TITLE
Warning: Creating default object from empty value 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#557]
`[DEC 15 13:20:31] Warning: Creating default object from empty value in /public/wp-content/plugins/publishpress-authors-pro/vendor/alledia/edd-sl-plugin-updater/EDD_SL_Plugin_Updater.php on line 342`

**Comment by ojopaul** [comment]
@stevejburge this seems to be a problem with a third party plugin and not PublishPress Authors

**Comment by stevejburge** [comment]
@andergmartins Could this be an issue with our updater?

**Comment by andergmartins** [comment]
@stevejburge yes, that file is a class on our update library.
@ojopaul this is the library: alledia/edd-sl-plugin-updater: https://github.com/publishpress/EDD-SL-Plugin-Updater/

**Comment by andergmartins** [comment]
I'm assigning it to me as well so I can take a look on the updater library

**Comment by ojopaul** [comment]
Oh, i didn't know it's under our control before.

**Comment by andergmartins** [comment]
@ojopaul this is the library https://github.com/publishpress/EDD-SL-Plugin-Updater

**Comment by andergmartins** [comment]
@ojopaul please, update the library and check if the issue still exists

**Comment by ojopaul** [comment]
The issue no longer exists. Thanks @andergmartins
