### ISSUE TITLE
PHP 7 Warning:  A non-numeric value encountered

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#560]
`27-Dec-2021 13:14:14 UTC] PHP Warning:  A non-numeric value encountered in /home/sitename/www/media/wp-content/plugins/publishpress-authors/src/modules/default-layouts/default-layouts.php on line 174`

**Comment by ojopaul** [comment]
@stevejburge , this issue is related to https://github.com/publishpress/PublishPress-Authors/issues/559 and as a result, the newly created PR will fix it. SO, maybe this should be closed in favour of that ?

**Comment by stevejburge** [comment]
Sure thing @ojopaul. Closing now
