### ISSUE TITLE
Add the ability to group / categorize Authors

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#58]
The field should have the following options:

- List of options
- Single or multiple selection
- Option to use as index: this allows to group the authors using the selected option as index of a list. Helpful to categorize authors in the layout or for other uses. Examples of categories that could be used: Author, Co-author, Translator, Contributor, etc.

This should allow to create layouts like this on the author box:

```
Authors: Yoshio, Barrett
Translator: Jarrod
```
Or display the value of the selected item in the box:

```
Authors:

   - Yoshio [Department: <selected_option>]
   - Jarrod [Departments: <selected_option1>, <selected_option2>]
```

**Comment by stevejburge** [comment]
One more request for this:

> I am looking to separate the main author and the co authors in the for loop.
> 
> Author:
> John Doe
> 
> Co Authors:
> Mary Jane
> Taylor Swift

**Comment by andergmartins** [comment]
The field could have a setting that when enabled will create two or more sections (one for each option) in the metabox to select authors where we can drag and drop authors on those sections. The result is something like the following prototype:

<img width="292" alt="Screen Shot 2020-06-15 at 14 14 17" src="https://user-images.githubusercontent.com/407131/84686678-cb1a6c00-af12-11ea-982f-2e9a70c344e7.png">

For creating that we have a custom field with 2 options: Author, and Co-authors. The option to group authors is enabled.

Only one field should have option activated. In order to active to another one, you need to deactivate the current one.

**Comment by andergmartins** [comment]
Maybe have a setting in the field to only show that for specific post types? So we could have different grouping options (or none) for different post types.

**Comment by stevejburge** [comment]
Thanks @andergmartins. Yes, would be a popular new feature

**Comment by stevejburge** [comment]
One more vote for this from a customer. They want to categorize the Authors for an eCommerce store

**Comment by stevejburge** [comment]
One suggestion from @heyjoecampbell

This could be used to define the main author, and also contributors: https://ahrefs.com/blog/trailing-slash/

![unnamed](https://user-images.githubusercontent.com/3868028/109009515-9ef7e300-767c-11eb-87ee-e56a68f96b50.jpg)

**Comment by stevejburge** [comment]
More from @heyjoecampbell

Showing contributors: https://praiseon.com/20-commitments-for-growing-your-faith-part-1
<img width="744" alt="Screen Shot 2021-02-24 at 2 02 18 PM" src="https://user-images.githubusercontent.com/3868028/109051821-ebf1ae80-76a8-11eb-8b0c-08556f85485b.png">

https://njcontentcreators.com/blog/activate-two-factor-authentication-for-stronger-security/
<img width="878" alt="Screen Shot 2021-02-24 at 2 04 31 PM" src="https://user-images.githubusercontent.com/3868028/109052098-3ecb6600-76a9-11eb-906d-d3107aef965b.png">

**Comment by andergmartins** [comment]
We got another request today from a user that wants to group authors as interviewed people and interviewers on the post.

`"Author A, Author B, interviewed by Author C"`

`"Author A interviewed by Author C, Author B"`

**Comment by stevejburge** [comment]
Thumbs up to this. It's something we should do

**Comment by stevejburge** [comment]
1 more request for this today:

> we also need to show three more individuals: the editor, audio director, and narrator; however, they must be differentiated by role, since we're not equal co-authors.

**Comment by heyjoecampbell** [comment]
The singular digital publishing term "Author" needs to be changed to the broad and inclusive term "Contributor(s)". 

A single post is likely to contain multiple content elements that were produced in collaboration with multiple content “contributors”.

Here's an example of the content elements and likely contributors:

**Text** - writer, editor, fact checker, content concept submitter 
**Images** - graphic designer, illustrator 
**Video** - camera person 1 & 2, video editor, color correction
**Podcast Media** - audio engineer, music producer, hosts
**General** - web administrator, project manager

Each "contributor" should receive credit for their contribution. 

This plugin could be the trailblazing tool of this fresh approach, providing the infrastructure to recognize “every content contributor”.

**Comment by stevejburge** [comment]
This is becoming our most-requested feature. From today:

> I want to add "Published by:" before the author. Then, add "Reviewed by", Then include the person that reviewed the article.

**Comment by stevejburge** [comment]
One more:

> For some posts on my blog I would like to have three different types of autor
> written by:
> Scientifically reviewed by:
> Medically reviewed by:

**Comment by stevejburge** [comment]
One more suggestion from @heyjoecampbell

![unnamed](https://user-images.githubusercontent.com/3868028/131526254-fb4a24a4-141d-445b-955d-946f83a7f468.png)

**Comment by ojopaul** [comment]
"So maybe we could try converting the Authors taxonomy adding the option for hierarchy = true for it? 

So no much changes would be needed, since a group would still be a taxonomy and the current code to filter or display them could probably mostly be reused.

so groups and authors would all be at the same taxonomy `author`.

...but that classifies authors globally, not by individual posts/series

**Comment by stevejburge** [comment]
From @andergmartins 

- New table for author groups/roles - new admin page for CRUD
- New DB table for the group, author, post relationship, but maybe post_id, group_id, term_taxonomy_id? Not all authors have user_id
- No need to convert author taxonomy in hierarchy for now
- Allow drag and drop among the categories, as the comment I highlighted before, keeping a UI close to what we have right now

**Comment by andergmartins** [comment]
For future reference: https://publishpress.slack.com/archives/C4TJSQY1G/p1652895065635289

Our questions at the moment are:

* Could the categories/groups of authors be specific per post type?
* What is the new criteria for determining which author (mapped to user) will be the one set on the post's `post_author` field? All the categories are candidate for that?
* From @agapetry: Or in a more general sense, user taxonomies. Why limit it to levels of authorship? This could be a way to identify users who are associated in some way with the content (role-players in a documented production process or administrative process, for example)... My point was that if you start defining multiple categories for authors (contributor, photographer, etc.), those indicate someone's involvement in the production of the content.  But there's no inherent reason to stop there.  The same mechanism could be used to map people's functional relationship to the content of the post... It would be nice to be done with the whole user <> author sync requirement and just store user_id directly.  Then the terms we store could be actual categories, not authors.

**Comment by stevejburge** [comment]
One more example here:
<img width="658" alt="Screen Shot 2022-10-19 at 9 10 27 AM" src="https://user-images.githubusercontent.com/3868028/196700404-c283c5c3-d145-4ed8-9c77-ddf56f447d5b.png">

**Comment by stevejburge** [comment]
One more example:
![320054017_862213484968087_84650459701619313_n](https://user-images.githubusercontent.com/3868028/208493418-4ee015c1-e95f-4c7f-8d60-52f0710a130c.jpg)

**Comment by NolanDolce** [comment]
Hello, I am also looking for this feature. Currently wordpress doesn't offer any similar feature in the Newspaper theme/TagDiv, and your plug-in doesn't offer what I need either (nor does any other plug-in). The suggestions in the thread seem to cover it, but just to add to the group of customers in need, I'm looking to be able to:

1. add primary author "written by" that links to his profile page (this person can have a WP account but may also be a guest)
2. add "medically reviewed by" person that links to his profile page (this person does not have a WP account)
3. add "updated by" person that links to his profile page (this person can have a WP account but may also be a guest)

All 3 should have an option to include a photo. 

Webpage example currently uses a custom field to add "medically reviewed by", without profile page template which would allow the profile page to populate all reviewed articles nicely: https://rareparenting.com/what-is-occupational-therapy-for-children/

Thank you!!

Nolan

**Comment by nmottet96** [comment]
Hi - I am also looking for these features:
- Written by (Already supported as "authors")
- Reviewed by

We also would like Author Schema to be supported:
- Author/person schema on posts AND author pages (https://schema.org/Person)
- ReviewedBy schema (https://schema.org/reviewedBy)

With Author Schema including more options, including:
[alumniOf](https://schema.org/alumniOf)
[nationality](https://schema.org/nationality)
[sameAs](https://schema.org/sameAs)
[jobTitle](https://schema.org/jobTitle)
and many more from https://schema.org/Person

Thank you!

**Comment by JohnSharkey** [comment]
Another vote for this! Being able to include a custom category to filter the author list would enable this software to be used to show a list of "staff" under a certain "department" category. It would save me from needing another plugin to do this, such as Staff List.
