### ISSUE TITLE
New translations

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#582]
French, Spanish, and Italian files to add to our releases:

[italian.zip](https://github.com/publishpress/PublishPress-Authors/files/8089025/italian.zip)
[french.zip](https://github.com/publishpress/PublishPress-Authors/files/8089022/french.zip)
[spanish.zip](https://github.com/publishpress/PublishPress-Authors/files/8089024/spanish.zip)

**Comment by andergmartins** [comment]
@stevejburge there are some files that seem to be translations for the readme file, not the plugin. Sorry, not sure were to put those translations:

![image](https://user-images.githubusercontent.com/407131/159528244-518214be-0066-439a-bdf0-3131a584f4c8.png)

I updated the Italian translation files in the plugin, btw.

**Comment by stevejburge** [comment]
@andergmartins No worries, we can ignore the readme files
