### ISSUE TITLE
Subscribers can't see Author pages

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#584]
This is an odd issue: https://wordpress.org/support/topic/subscriber-role-does-not-have-access-to-author-pages/

I can confirm this when logged in as a Subscriber and viewing a page like this /author/steve/
<img width="1232" alt="Screen Shot 2022-02-24 at 10 16 17 AM" src="https://user-images.githubusercontent.com/3868028/155552350-ed140241-6f11-49e4-9971-f543c6993c87.png">

And when logged out:
![Screen Shot 2022-02-24 at 10 16 54 AM](https://user-images.githubusercontent.com/3868028/155552458-4d32e5ce-bfa6-4c89-9dc0-eb9c3a4f29cb.png)

**Comment by ojopaul** [comment]
One more report of this today:

> Authors who have access as authors are not able to view their posts under "mine".

![Firefox_Screenshot_2022-03-22T14-29-51 117Z-fea8ffc3baa90682b99f99d709b1754d](https://user-images.githubusercontent.com/3868028/159546888-99a6d7b2-869f-4a71-a700-ae241cb6fc6a.png)
