### ISSUE TITLE
"Mine" counter is incorrect

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#591]
We've had some issues reported with the "Mine" counter on posts. For example, here's an example of "6" when there's only 5 posts:

![Screen Shot 2022-03-07 at 3 00 04 PM](https://user-images.githubusercontent.com/3868028/157108862-f9e3b62b-e6ff-4929-9b2d-d91017a78627.png)

Here's an example of "0" when there's 1 post for this user:
![Screen Shot 2022-03-07 at 3 03 39 PM](https://user-images.githubusercontent.com/3868028/157109365-4ee02a6c-156b-43a4-b0e7-22a39b6b4ca9.png)

**Comment by stevejburge** [comment]
One more report of this today:

> Authors who have access as authors are not able to view their posts under "mine".

![Firefox_Screenshot_2022-03-22T14-29-51 117Z-fea8ffc3baa90682b99f99d709b1754d](https://user-images.githubusercontent.com/3868028/159546888-99a6d7b2-869f-4a71-a700-ae241cb6fc6a.png)

**Comment by ojopaul** [comment]
@stevejburge the second issue, `"Authors who have access as authors are not able to view their posts under "mine".` is unrelated to the mine counter but instead, same as #584 issue. So, i'll move it there so this commit can address the main issue for which it was created.

**Comment by stevejburge** [comment]
good work, thanks @ojopaul
