### ISSUE TITLE
Add metabox to control author display

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#60]
Another similar plugin to PublishPress authors offers a metabox to control author display on that page. It should be possible to disable it here:
<img width="268" alt="Screen Shot 2019-12-13 at 9 51 14 AM" src="https://user-images.githubusercontent.com/3868028/70808784-6c6f0c80-1d8e-11ea-9170-840e33883c03.png">

**Comment by ojopaul** [comment]
@stevejburge should we simply add a checkbox here with label "Disable Author Display"?

Or you can explain if this is a new metabox and what the dropdown option will be?

<img width="268" alt="hgghhg" src="https://user-images.githubusercontent.com/92122385/161579642-a28bcd23-7e6c-4471-b168-dfde302d5b12.png">

**Comment by stevejburge** [comment]
@ojopaul Good question. Let's use the same metabox and add this underneath.
