### ISSUE TITLE
Description field shows for Authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#605]
Compare this screen for an admin, and as a low level user. The Author see a "Description" field that the admin does not. Should we remove this?
<img width="833" alt="Screen Shot 2022-03-22 at 1 25 01 PM" src="https://user-images.githubusercontent.com/3868028/159539734-18e8ee4e-00e2-4c11-82c4-e33c1ca8967c.png">
<img width="830" alt="Screen Shot 2022-03-22 at 1 24 37 PM" src="https://user-images.githubusercontent.com/3868028/159539739-5fca8b64-ad85-4838-9d89-7f1cfb82b8ff.png">

**Comment by andergmartins** [comment]
@stevejburge Yes, good catch. The description is not needed since we have the Biographical Info field. Lets remove it.

**Comment by andergmartins** [comment]
@stevejburge good catch. I was able to replicate it clicking on the tab Image then switching back to General. The field that was hidden is revealed. I will fix it to keep it hidden.
