### ISSUE TITLE
Disable Free version with Pro is active

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#615]
Let's make sure to the disable the Authors Free version when Authors Pro is active

**Comment by ojopaul** [comment]
@andergmartins what's the best approach to take on this, should i check if 'PP_AUTHORS_PRO_LOADED' is define in free plugin and deactivate the plugin?

In TaxoPress, there's a function that constantly check if PRO plugin is active in free plugin and i simply deactivate the the plugin in the function.

**Comment by andergmartins** [comment]
Sorry for the delay @ojopaul, but we still need to define the standard approach we will take for all the plugins... https://publishpress.slack.com/archives/CG676C66A/p1648760128970879
I hope we can work on that soon

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Capabilities/pull/331
