### ISSUE TITLE
Fatal error: Uncaught Error when "Create missed post authors" button is clicked

### ISSUE THREAD

**Issue by ojopaul** [publishpress/PublishPress-Authors#623]

**Comment by andergmartins** [comment]
Let's give more context to this issue, just in case we need more information in future.

![image](https://user-images.githubusercontent.com/407131/163019531-332ee125-46ec-489b-b402-4aeb77e3040e.png)

>Fatal error: Uncaught Error: Call to undefined function admin_ur1l() in /www/kinsta/public/plugindev/wp-content/plugins/publishpress-authors/src/modules/multiple-authors/multiple-authors.php on line 1715
