### ISSUE TITLE
Default avatar for authors not working in dropdown

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#68]
The default avatar works well in the "Authors" page
<img width="721" alt="Screen Shot 2019-11-12 at 9 28 50 AM" src="https://user-images.githubusercontent.com/3868028/68679994-df3a5d00-052e-11ea-99dd-09f75e2af3d8.png">

Not so well in the dropdown inside posts:
<img width="276" alt="Screen Shot 2019-11-12 at 9 28 25 AM" src="https://user-images.githubusercontent.com/3868028/68679953-d0ec4100-052e-11ea-8c7e-7a46209d7a00.png">

**Comment by htmgarcia** [comment]
@stevejburge probably this was fixed. The images loads fine with latest free version:
<img width="252" alt="Screen Shot 2020-04-14 at 16 40 05" src="https://user-images.githubusercontent.com/4999794/79277059-b831df80-7e6e-11ea-95f5-7a000b472ae0.png">

**Comment by htmgarcia** [comment]
Please re-open if needed.

**Comment by stevejburge** [comment]
@htmgarcia Can you try again with a guest author?

I see this still:
<img width="773" alt="Screen Shot 2020-04-17 at 1 39 23 PM" src="https://user-images.githubusercontent.com/3868028/79597834-fae2fa00-80b0-11ea-993d-a1206eee1e85.png">

**Comment by htmgarcia** [comment]
@stevejburge guest authors default image loads fine in my end. I'm using Chrome as browser:
<img width="326" alt="Screen Shot 2020-04-17 at 14 57 21" src="https://user-images.githubusercontent.com/4999794/79609144-d50f2280-80bb-11ea-8eba-f92821d6bc58.png">
Any chance to reproduce the issue in a test site in CW? Probably I'm missing something.

**Comment by stevejburge** [comment]
@htmgarcia Firefox for me. This normally happens for the first guest author on a site

**Comment by htmgarcia** [comment]
@stevejburge tested in a complete new fresh site in Firefox. Sorry. Still not able to reproduce the issue: https://youtu.be/H4gJApd7tRc

**Comment by stevejburge** [comment]
OK, thanks @htmgarcia 

After more testing, I think it is an adblock issue. This images loads from Gravatar and most browser adblockers will block Gravatar.

**Comment by htmgarcia** [comment]
@stevejburge sounds fair. I'll keep an eye and reopen if the issue is back.
