### ISSUE TITLE
No author feature produces a WSOD with PublishPress Permissions Installed

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#7]
`Uncaught Error: Call to a member function has_cap() on boolean in /app/public/wp-content/plugins/publishpress-multiple-authors/modules/multiple-authors/multiple-authors.php:1019 Stack trace: #0 /app/public/wp-includes/class-wp-hook.php(288): MA_Multiple_Authors->filter_map_meta_cap(Array, 'edit_post', 0, Array) #1 /app/public/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array) #2 /app/public/wp-includes/capabilities.php(618): apply_filters('map_meta_cap', Array, 'edit_post', 0, Array) #3 /app/public/wp-content/plugins/presspermit-pro/classes/PublishPress/Permissions/UI/Dashboard/ItemExceptionsUI.php(133): map_meta_cap('edit_post', 0, 24) #4 /app/public/wp-content/plugins/presspermit-pro/classes/PublishPress/Permissions/UI/Dashboard/PostEdit.php(165): 

The trace goes back here:
/wp-content/plugins/publishpress-multiple-authors/modules/multiple-authors/multiple-authors.php: 1019

`

**Comment by andergmartins** [comment]
I'm closing this since we removed the no-author feature.
We can double check this if we find a way to solve the conflicts to bring the feature on again.

Related to #29
