### ISSUE TITLE
SEO Framework plugin integration errors

### ISSUE THREAD

**Issue by 1pix** [publishpress/PublishPress-Authors#709]
Hi,

I have some errors with the SEO Framework.
wp 6.0
php. 8.0
seo framework: 4.2.4
publishPress Authors 3.17

---

1. It seems that the function to set the archive title for authors is deprecated and throw an error:

@see https://github.com/publishpress/PublishPress-Authors/blob/59079119bc6ee208ab6a6325513450d8b291749d/src/modules/seoframework-integration/seoframework-integration.php#L89

**Proposal**
The plugin owner recommends using `the_seo_framework_generated_archive_title_prefix` and `the_seo_framework_generated_archive_title` instead.

---

2. Some warning also in ` setArchiveTitle()`
https://github.com/publishpress/PublishPress-Authors/blob/59079119bc6ee208ab6a6325513450d8b291749d/src/modules/seoframework-integration/seoframework-integration.php#L94

**Error**: `Undefined property: WP_Post_Type::$term_id`

**Comment by stevejburge** [comment]
thanks for the detailed bug report @1pix
