### ISSUE TITLE
Wrong Permission in Documentation

### ISSUE THREAD

**Issue by mxkyb** [publishpress/PublishPress-Authors#722]
Not related to the source code, but couldn't find a better place to report. There is a problem in your documentation here: https://publishpress.com/knowledge-base/admin-area-permissions/

It says:

> **ppma_edit_post_authors**: this controls who can access their “Authors Profile” link.

It should say instead:

> **ppma_edit_own_profile**: this controls who can access their “Authors Profile” link.

**Comment by stevejburge** [comment]
Ooops, thanks for catching that @mxkyb
