### ISSUE TITLE
Allow plugins and themes to hook into the rest api response

### ISSUE THREAD

**Issue by mxkyb** [publishpress/PublishPress-Authors#725]
**Is your feature request related to a problem? Please describe.**
I would like to include author avatars into the plugins rest api response. Instead of registering my own rest field, I would like to be able to extend the existing `authors` field in the post response.

As the use case potentially could be broader than just adding avatars, I'd like to propose implementing a filter. This would allow every plugin or theme author to modify the publish press rest api response.

```php
return $authorsData = apply_filters('pp_rest_api_authors_data', $authorsData);
```

As an alternative it would be possible to do something like this, which is obviously far less elegant.

```php
register_rest_field(
    'post',
    'authors-avatars',
    [...]
);
```

**Comment by stevejburge** [comment]
Thanks so much for this @mxkyb 

We have an upcoming release milestone which is focused on nothing but better support for the REST API. I've attached this to that milestone

**Comment by ojopaul** [comment]
This is already fixed
