### ISSUE TITLE
A term with the name provided already exists in this taxonomy.

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#73]
If you try to map a user twice, you get this confusing feedback: "A term with the name provided already exists in this taxonomy."
![Screen Shot 2019-09-25 at 11 39 09 AM](https://user-images.githubusercontent.com/3868028/65616520-2b364000-df89-11e9-8e39-11143abe867c.png)

**Comment by andergmartins** [comment]
Fixed on #64. We decided to not allow mapping the same user to multiple authors.
