### ISSUE TITLE
Consistency in settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#732]
On other tabs we do this:
<img width="648" alt="Screen Shot 2022-06-20 at 1 47 21 PM" src="https://user-images.githubusercontent.com/3868028/174655392-5d71eea2-5094-4ea8-9eff-95eb5bbd4d6e.png">

Let's keep it consistent:

- This will display the author description
- This will display the author avatar
- This will display post featured image
- etc

<img width="469" alt="Screen Shot 2022-06-20 at 1 47 48 PM" src="https://user-images.githubusercontent.com/3868028/174655439-94f3e294-0957-4eb8-8ab2-3873ffef5e9d.png">

The label's look good except we can use "category" for consistency:

<img width="551" alt="Screen Shot 2022-06-20 at 1 49 12 PM" src="https://user-images.githubusercontent.com/3868028/174655636-2e30a5c9-fb24-44a4-9361-785cc193292a.png">

**Comment by stevejburge** [comment]
Sorry, I'm going to be a real pain ...


This will display the featured image.
This will display the excerpt.
This will display the authors.
This will display the published date.
This will display the comment count.
This will display the categories.
This will display the tags.
This will display the read more link.

**Comment by ojopaul** [comment]
Fixed in https://github.com/publishpress/PublishPress-Authors/pull/745
