### ISSUE TITLE
Change the hidden user feature to a setting

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#743]
I think this hidden user feature would be best as a setting.

It is confusing to have it appear constantly in the UI:
<img width="664" alt="Screen Shot 2022-06-22 at 11 53 57 AM" src="https://user-images.githubusercontent.com/3868028/175077097-b0182f06-24f2-4063-9db6-36043ae39d27.png">

**Comment by ojopaul** [comment]
@stevejburge 
1. Will this title go:
> Show default author selection?

2. Should this be checked by default or not?

**Comment by stevejburge** [comment]
Thanks @ojopaul 

1. I think a good title will be "Fallback user for Guest Authors". 

The label can be: "If you only have Guest Authors selected for a post, this user may be used as a fallback. WordPress sometimes requires a WordPress user to be assigned to each post. This user will not be visible on the front of your site."

2. I believe our current setup always forces you this to be active if you chose a Guest Author so this will always be active.
