### ISSUE TITLE
Title for the author box" is "Author" by default - should be "Authors"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#75]
> "Title for the author box" is "Author" by default. It should also automatically default to "Authors" (Plural) when there are 2+ authors. Then any alternative text added in this setting (e.g., "This article was written by:") would override the default ("Author/s").

**Comment by andergmartins** [comment]
We faced this issue again today. Maybe we should have two settings fields? One for singular and another for plural. The same approach we decide to use here we need to for the Post Author widget.

Another option is to remove this setting field and leave that for being handled in the layout code. But the free version wouldn't have that option, until we move custom layouts to it.

**Comment by andergmartins** [comment]
Related to #282
