### ISSUE TITLE
Rethinking how we handle layouts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#758]
Currently the Free version uses files, and the Pro version uses the database for storing the layouts.

We have come across some issues with this:
- It has hard to use PHP inside the Pro layouts
- The Twig version we use is somewhat old
- We don't make it easy for other themes and plugins to add their own layouts

How can we improve our layout system?

**Comment by stevejburge** [comment]
From Paul:

> Starting with allowing option to add more layout directly will be a great starting point …and the best way a designer can have 100% control on the php and full template is when we accept other than twig

**Comment by stevejburge** [comment]
From Anderson:

> 
> Whatever tech approach we decide to do the change from DB/Twig layouts to PHP files (and optional twig), I suggest keeping compatibility with the Pro layouts users have on the DB. I think some users might not want to create PHP files, considering they already have their layout working well. But this could be optional and disabled for new installations. I suggest keeping it enabled by default for updates.
> If you wanna keep this as a Pro only feature, be careful to not add template overriding support to the free package, only to the Pro. Maybe this is only a change for the Pro package? If you just want to remove Twig requirement, Free layouts can easily be moved from Twig to PHP files. Just make sure Twig is not used elsewhere on the widget or settings page.
> In the Free package there is a filter pp_multiple_authors_author_layouts that is used by Pro to override the PHP files to DB based custom layouts. But some additional filters/actions are called in the Pro as well when saving the layouts, etc. That could still be used to add support to theme based template overrides (PHP files on themes), if Pro only.

**Comment by ojopaul** [comment]
Closing this for https://github.com/publishpress/PublishPress-Authors/issues/896
