### ISSUE TITLE
PublishPress Authors needs its own "Authors" widget

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#76]
If more than one person is added as an author, the other person won't get credit in the default "Authors" widget
https://wordpress.com/support/widgets/authors-widget/

![image](https://user-images.githubusercontent.com/3868028/88465827-1faaf280-ce94-11ea-8854-f5bf0cb8ecda.png)

Settings:

![image](https://user-images.githubusercontent.com/3868028/88465829-276a9700-ce94-11ea-9e81-74334e46bc27.png)

**Comment by stevejburge** [comment]
One more request:

> I need a widget to show a list of authors in the sidebar either by number of posts by each author or by providing their ID's. Similar to popular posts widget or recent posts widget but for authors.
> 
> The current widget will only show the author assigned to the post.

**Comment by mdmag** [comment]
@andergmartins  Hey Anderson,
I have cloned this repo and have run: `composer install `and then I added `AuthorsListWidget` class in `Core` folder which extends the default `Widget` class with overriding some methods.
Now, I am stuck in how to require this class to be loaded. Should I do something with composer because I can't find any direct require for the default `Widget` class.

**Comment by mdmag** [comment]
I got it I think. 
I found ps-4 in composer.json that autoloads all files in core folder.

**Comment by andergmartins** [comment]
Hi @mdmag, cool, yeah we use PSR-4 class loading there 👍

**Comment by mdmag** [comment]
@andergmartins When I list my authors with my widget and go to their url, it goes correctly to their url but the plugin throws an error in this page [](https://pasteboard.co/JkPVWOa.png)

**Comment by mdmag** [comment]
I found there is an issue already opened for that #156

**Comment by andergmartins** [comment]
Hi @mdmag, thanks I just merged the fix to the development branch. Please, could you double check?
