### ISSUE TITLE
Filters for Author List

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#780]
We've had several requests for this now.

Here's a typical example:

> I've installed the free version of PublishPress Authors and have created 800 Authors and Guest Authors. I've added a list of these 800 authors to a dedicated 'Authors' page. However, since we have so many, we'd like to provide a way that our Users can search / filter through the list. Here's an example website that has the functionality that what we're looking for (although it doesn't need to be quite so comprehensive): [https://migrationresearch.com/experts]

Here's another:

> in your Authors plugin is it possible to have a page with a grid of all authors and filter them by fields that I add, for example filter by Name or Address or Year of born ?

**Comment by ojopaul** [comment]
@stevejburge Maybe we should add the layout in the link https://migrationresearch.com/experts too?

It seems to be a nice layout and will come in handy when people started using our author list layout to showcase authors.

**Comment by stevejburge** [comment]
Thanks @ojopaul Yes, that's not a bad idea. Having one layout with rows would give users something else to work from.

**Comment by ojopaul** [comment]
@stevejburge This will be needed for documentation purpose

So, we added new parameters:
- `search_box`. When this parameter is set to 'true', a search box will be displayed to enable author search. Example usage `[publishpress_authors_list layout="authors_recent" search_box="true"]`
- `search_field`. This is an additional filter added to enhance search. It enable option to provide valid field names separated by comma(,) and these fields will be available as option for user to select from to limit their search.

It basically accept all fields and including custom fields like:
- first_name
- last_name
- user_email
- user_url
- description and just any other custom field slug.

Example usage: `[publishpress_authors_list layout="authors_recent" search_field="first_name,last_name,description"]`
