### ISSUE TITLE
Link in "Permissions for Orphan Posts" with different name

### ISSUE THREAD

**Issue by JulieBanu** [publishpress/PublishPress-Authors#79]
Step 1:   Go to "Permissions" menu
Step 2:   Select Permissions for Orphan Posts" menu item
Step 3:   click "have posts with no authors" link
 
Note:   The link opens "Change WordPress Users to Guest Authors" menu item   from "Authors Profiles" menu. Because this feature is not available   anymore, maybe this phrase should be removed or rephrased.

![NoAuthorsLinkFromPermissions](https://user-images.githubusercontent.com/62157750/78187703-c2da8680-7423-11ea-9fda-fd2522fc93e8.PNG)

**Comment by andergmartins** [comment]
Waiting for #29
