### ISSUE TITLE
Allow users to edit "Authors Recent" and "Authors Index"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#801]
Can we add a setting, or even just documentation, explaining how users can modify "Authors Recent" and "Authors Index"

**Comment by ojopaul** [comment]
@stevejburge this will come i handy when making documentation

Authors  layout is located in:
`/wp-content/plugins/publishpress-authors/src/twig/author_layout/
`
So, to overwrite the layout, the layout file should be copy from the above directory to:
`/wp-content/themes/your-theme-name/publishpress-authors/twig/`
