### ISSUE TITLE
Add descriptive text to Authors links

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#807]
One customer has requested that we automatically add descriptive text to Authors links

They shared this SEO result for the link for an author at the bottom of the post:

<img width="869" alt="Screen Shot 2022-07-29 at 3 38 05 PM" src="https://user-images.githubusercontent.com/3868028/181832197-32d5b4c7-7af0-44ec-a73f-19362f390975.png">

**Comment by ojopaul** [comment]
@stevejburge the pages author links are inside layout template. So, this should be updated to add title attribute (if that's what the description means).

For our custom template like authors page and default layouts, i'll update them to add this but for database layouts, they simply need to update the layout to add it.

**Comment by stevejburge** [comment]
OK, thanks @ojopaul 

Yes, let's just do this for the new layouts
