### ISSUE TITLE
Allow user to change author pages headers (H1, H2, H3, H4, H5, H6)

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#832]
Listening to use feedback, quite a few of them have asked to change the size of certain layout features such as the post titles

Could we consider allowing users to set the H1, H2, H3, H4 etc for features on the Author Pages?

**Comment by ojopaul** [comment]
@stevejburge 
In both layouts, `h1` is been used in author page title and `h2` is been used in post title. For both, how do you want this to be implemented? Providing a selection dropdown in author pages settings to select the header for both use cases?

**Comment by stevejburge** [comment]
Yes, I think so. We might consider doing a width and / or height option for featured images too. This is Author Pages on PublishPress.com
![Uploading Screen Shot 2022-08-09 at 12.03.42 PM.png…]()

**Comment by ojopaul** [comment]
The image wasn't uploaded before you posted the comment @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Sorry, re-uploaded
