### ISSUE TITLE
Add avatar_url to Post Author REST API

### ISSUE THREAD

**Issue by Eufranio** [publishpress/PublishPress-Authors#837]
**Is your feature request related to a problem? Please describe.**
I want to be able to get the avatar of a guest user.

**Describe the solution you'd like**
The author returned in the REST API could include the url of the avatar, or maybe add a new REST API endpoint so we can retrieve the avatar of a guest user.

**Describe alternatives you've considered**
Retrieving the avatar of the normal post author. Did not work.

**Additional context**
None.

**Comment by stevejburge** [comment]
@Eufranio Thanks. Please share any code you have so our team can understand the use case here

**Comment by Eufranio** [comment]
At the moment I'm just using the wordpress' REST API on my mobile app, but the authors info is missing this avatar data.

**Comment by ojopaul** [comment]
@Eufranio You'll need to provide more information on the request.

How are you accessing this rest api?

**Comment by Eufranio** [comment]
I am using the wordpress' REST API to get the post data, by sending a request to `website/wp/v2/posts/?context=view`. The request returns the normal post data, plus the authors data just like this: https://publishpress.com/knowledge-base/authors-rest-api/

The problem is that there's no way for me, with that data, to get the avatar of the author.

**Comment by ojopaul** [comment]
Thanks for clearer explanation @Eufranio 

Author's avatar URL will be included in the rest response in the next release.
