### ISSUE TITLE
PublishPress Authors and Easy Digital Downloads version 3

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#839]
There's a bug that I've had difficulty replicating:

- PublishPress Authors Free and Easy Digital Downloads version 3
- When Authors is enabled, some products can not be edited

The error appears like this:

`2022/08/08 22:09:32 [error] 65885#65885: *4512440 FastCGI sent in stderr: "PHP message: PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /www/publishpress_134/public/wp-includes/wp-db.php on line 1254PHP message: PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0" while reading response header from upstream, client: 177.40.118.36, server: publishpress.com, request: "GET /wp-admin/post.php?post=98972&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-publishpress.sock:", host: "publishpress.com:16342", referrer: "https://publishpress.com/wp-admin/edit.php?post_type=download"`

It only happens on some products, and so far I've only see it on the PublishPress site

**Comment by ojopaul** [comment]
@stevejburge is the new author page enabled on the site? If so, can you disable the author page and see if the issue is gone?

**Comment by stevejburge** [comment]
@ojopaul WordPress drives me crazy sometimes :)

I disabled the Author Pages and EDD works again. Then re-enabled Author Pages, and EDD still works.

I don't understand :)
