### ISSUE TITLE
Show all profile fields option in author box editor

### ISSUE THREAD

**Issue by ojopaul** [publishpress/PublishPress-Authors#909]
This will need further discussion but i'm putting it here so as not to forget.

Maybe we should show all profile fields options in the editor to enable adding profile fields value

**Comment by stevejburge** [comment]
Yes, this will be key for Pro users. How can we allow users to add fields to the Author Box?

**Comment by ojopaul** [comment]
We'll add profile fields tab to the editor.

I'll be able to decide on approach for showing/hiding field and the content when working on it which can be improved after feedback.

@stevejburge

**Comment by stevejburge** [comment]
Thanks. Maybe some field types are available in the Free version and more in the Pro version.

**Comment by ojopaul** [comment]
@stevejburge Are we implementing it now or next phase?

**Comment by ojopaul** [comment]
Fixed by https://github.com/publishpress/PublishPress-Authors/issues/896
