### ISSUE TITLE
Add shortcode column to author boxes list?

### ISSUE THREAD

**Issue by ojopaul** [publishpress/PublishPress-Authors#920]
Should we add shortcode column to author boxes like that display data` like [publishpress_authors_box layout="ppma_boxes_862"]`

![shortcode](https://user-images.githubusercontent.com/92122385/193575150-405cf8e6-68b1-42e5-a2d3-8bebe57e7768.jpg)

**Comment by stevejburge** [comment]
Thumbs up for this

**Comment by ojopaul** [comment]
Fixed https://github.com/publishpress/PublishPress-Authors/pull/919
