### ISSUE TITLE
Move author box preview above the settings, or remove sidebar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#926]
At the moment, we have 4 columns on the screen. Let's try either placing the preview about the settings, or let's remove the right sidebar:
<img width="1581" alt="Screen Shot 2022-10-03 at 3 46 54 PM" src="https://user-images.githubusercontent.com/3868028/193665600-ef252655-713d-47ed-a0b9-60eb678b63c8.png">

**Comment by ojopaul** [comment]
Fixed
