### ISSUE TITLE
What to do with "Author Boxes" area in Settings

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#942]
Do we leave these in place or are they redundant now? Do we keep just the first 3 settings?

<img width="691" alt="Screen Shot 2022-10-12 at 4 24 39 PM" src="https://user-images.githubusercontent.com/3868028/195440818-e2c08bbc-ef1a-4509-bba7-bba804da7346.png">

**Comment by ojopaul** [comment]
@stevejburge The legacy layout still uses the settings.

**Comment by stevejburge** [comment]
@ojopaul Maybe we keep the on/off box at the top?

Then there is a new/legacy choice underneath?
