### ISSUE TITLE
Add the Post Count 

### ISSUE THREAD

**Issue by andergmartins** [publishpress/PublishPress-Authors#95]
If a user is set as author before we install Authors and for any reason its related taxonomy term is not set, the posts count returns 0.

We need to double check if it is working well for other post types and guest authors.

**Comment by stevejburge** [comment]
Currently we just hide the post count:
<img width="915" alt="Screen Shot 2020-08-10 at 10 06 39 AM" src="https://user-images.githubusercontent.com/3868028/89791365-3c306700-daf1-11ea-8caa-720e9535991c.png">

It would be good to add it back.

**Comment by andergmartins** [comment]
I was checking and it only counts if the post is published. It is a limitation by WordPress.
I'm adding the column back to the Authors list and adding a bulk action that allows to update that number if required.
