### ISSUE TITLE
Hide settings for new layouts, not Legacy layouts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#954]
We do a good job of hiding the Legacy settings, but shouldn't they appear when a Legacy option is chosen (and hide for others)

<img width="539" alt="Screen Shot 2022-10-14 at 9 20 25 AM" src="https://user-images.githubusercontent.com/3868028/195857212-2fa11324-6e42-4ffc-8861-d9851403a696.png">

**Comment by ojopaul** [comment]
@stevejburge They should appear, can you check console to see if you have any error when legacy layout are selected?

In my testing, they show when legacy layout is selected

**Comment by ojopaul** [comment]
Oh, reverse seems to be the case.

The settings show up when non legacy is selected.

Will fix that

@stevejburge
