### ISSUE TITLE
Remove Legacy options and "Layouts" menu

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#960]
Can we remove or hide the "Layouts" menu in the plugin?

Maybe it can be a setting in the admin area? "Enable legacy "Layouts" feature:"

We can put it here; https://github.com/publishpress/PublishPress-Authors/issues/1020

**Comment by ojopaul** [comment]
@stevejburge you want us to remove the layout by default even for existing users?

That is, after upgrade they had to enable it in settings to see layout menu?

**Comment by stevejburge** [comment]
@ojopaul Is it possible to leave enabled for current users, but disable for new users?
