### ISSUE TITLE
Add a parameter to limit number of authors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#993]
We've had one request for a parameter to limit number of authors on a page:

> In terms of the number of authors, we want to limit the query itself rather than just paginate it. There are many, many authors on this site that published articles YEARS ago and are not active authors. We wants to display those that are more active (for example, those who published in the last year)

https://publishpress.com/knowledge-base/author-pages/

**Comment by ojopaul** [comment]
1. Add post year limit parameter
2. Add number of posts parameter

**Comment by ojopaul** [comment]
### Update
1. We added new parameter [publishpress_authors_list last_article_date="1 year ago"] that accept english date value like 1 week ago, 1 month ago, 6 months ago, 1 year ago etc to limit author list to users with a published post within a specific period.
2. We added more filters to multiple_authors_get_all_authors
