### ISSUE TITLE
Missing strings in the files .pot of Author PRO

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Authors#995]
Hi,

I'm checking the language folder for making the translations and some strings are missing  in the files .pot of Author PRO
Please, review or refresh it, because I so that using the legacy from free version and checking the Pro.pot file some strings are not present in both Free and pro.pot

Thanks,
Angelo

**Comment by ojopaul** [comment]
Thanks @wocmultimedia I've added refreshing language pot file to release checklist.

It'll be fix from next release.
