### ISSUE TITLE
Allow Author list to have 2 columns for custom layout

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Authors#996]
For example, I create a custom layout using the Author box. And I want to use that custom layout for Author list using shortcode. It will show 1 column layout like this
![image](https://user-images.githubusercontent.com/83811723/197691272-c26e2ff3-0292-49ab-84c5-d820c42c81a7.png)

It will be better if we can allow the user to have 2 columns layout in Author list

**Comment by ojopaul** [comment]
### Update:
You can define the number of layout columns by using layout_columns="2" to show authors in 2 column.

[publishpress_authors_list layout="boxed" layout_columns="2"]
