### ISSUE TITLE
Authors_Iterator call in Author_box.php assumes that $post global is populated (which it isn't sometimes)

### ISSUE THREAD

**Issue by c0ntax** [publishpress/PublishPress-Authors#999]
## Expected Behavior

Using the following shortcode should always work

`<?= do_shortcode(sprintf('[publishpress_authors_box layout="inline" show_title="false" post_id="%d"]', get_the_ID())) ?>`

## Current Behavior

In most templates on my site, it does, but there are been some very specific instances (when a post is referenced within a post) where notices are thrown:

NOTICE: TRYING TO GET PROPERTY 'ID' OF NON-OBJECT IN /VAR/WWW/blablabla/WEB/CONTENT/MU-PLUGINS/PUBLISHPRESS-AUTHORS/SRC/CORE/CLASSES/AUTHORS_ITERATOR.PHP ON LINE 50

No post ID provided for Authors_Iterator constructor. Are you not in a loop or is $post not set? in 

## Possible Solution

It seems that the issue stems from this line here:

https://github.com/publishpress/PublishPress-Authors/blob/development/src/core/Traits/Author_box.php#L232

Although an optional `$post_id` is provided to the `get_author_box_markup()` method and it is used to populate a `$post`, neither the post id is passed to that method, or the $post made global (yuck) so the iterator can't work.

Possible solution: `$authors_iterator = new Authors_Iterator($post_id ?? 0, $archive);`

I don't know enough about the codebase to know if this would have any unintended side effects (i.e. maybe there was a reason why the post id was being forced to 0 there?)

## Steps to Reproduce (for bugs)

Hard to say, but I've noticed these notices being thrown when there there is a post within a post (i.e. an article has boxes with links to other articles that happen to want to display the author(s) name in it)

## Context

I want to be able to include the authors' names from other posts within a post.

## Your Environment

* Version used: 3.30.0
* Browser Name and version: Chrome 106.0.5249.119 (Official Build) (64-bit) 
* Operating System and version (desktop or mobile): ubuntu 22.04
* Link to your project:

**Comment by ojopaul** [comment]
Thanks @c0ntax

The issue and linked PR will be review and included in the next release.
